### ISSUE TITLE
Include grouped industry constraints

### ISSUE THREAD

**Issue by ActurialCapital** [robertmartin8/PyPortfolioOpt#10]
Hi,
Is there a way to include a portfolio optimisation with grouped by industry constraint?
for example:
- Between 0 and 10% of my portfolio weights have to be in industry "Technology"
- Between 15% and 30% of my portfolio weights have to be in industry "Energy"

A very good example is shown [here](https://stackoverflow.com/questions/44515880/scipy-portfolio-optimization-with-grouped-by-industry-bounds), which uses Scipy as well.
Thanks

**Comment by robertmartin8** [comment]
Hi,

Currently this is not supported. The link you've provided is very interesting, and it's great to see that they're using scipy. However it looks a little bit clunky: particularly their `mapto_constraints` function. Thus I am slightly worried about how this could be suitably generalised to fit within the `PyPortfolioOpt` API. However, if anyone would like to try to implement this, I'd definitely consider a pull request!

Robert

**Comment by schneiderfelipe** [comment]
@ActurialCapital An alternative way of controlling allocations based on industries might be using the [new Black-Litterman model](https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html) with [views](https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html#views) based on industry estimates.

Instead of fixing amounts, you would say e.g. the energy sector will outperform the general market by 10%. This is a zero-sum vector with constant positive values on the companies in the energy sector and constant negative values on all other companies:

```python3
# energy sector is comprised of companies 4 and 5 (starting from 0)
P = np.array(
    [
        ...
        [-1/8, -1/8, -1/8, -1/8, 1/2, 1/2, -1/8, -1/8, -1/8, -1/8],
        ...
    ]
)
```

I know it's not what you meant, but it's an effective way of handling this.

**Comment by robertmartin8** [comment]
@ActuarialCapital

Since the release of 1.0.0, this has been possible:

```python
    sector_mapper = {
        "GOOG": "tech",
        "AAPL": "tech",
        "FB": "tech",
        "AMZN": "tech",
        "BABA": "tech",
        "GE": "utility",
        "AMD": "tech",
        "WMT": "retail",
        "BAC": "fig",
        "GM": "auto",
        "T": "auto",
        "UAA": "airline",
        "SHLD": "retail",
        "XOM": "energy",
        "RRC": "energy",
        "BBY": "retail",
        "MA": "fig",
        "PFE": "pharma",
        "JPM": "fig",
        "SBUX": "retail",
    }

   # Upper and lower bounds for sectors
    sector_upper = {
        "tech": 0.2,
        "utility": 0.1,
        "retail": 0.2,
        "fig": 0.4,
        "airline": 0.05,
        "energy": 0.2,
    }
    sector_lower = {"utility": 0.01, "fig": 0.02, "airline": 0.01}

    ef = EfficientFrontier(mu, S)
    for sector in sector_upper:
        is_sector = [v == sector for k, v in sector_mapper.items()]
        # Sum of weights from that sector has to be less than the upper bound
        ef.add_constraint(lambda w: cp.sum(w[is_sector]) <= sector_upper[sector])
    for sector in sector_lower:
        is_sector = [v == sector for k, v in sector_mapper.items()]
        ef.add_constraint(lambda w: cp.sum(w[is_sector]) >= sector_lower[sector])

    weights = ef.min_volatility()

    for sector in list(set().union(sector_upper, sector_lower)):
        sector_sum = 0
        for t, v in weights.items():
            if sector_mapper[t] == sector:
                sector_sum += v
        print(sector, sector_sum)
        assert sector_sum <= sector_upper.get(sector, 1) + 1e-5
        assert sector_sum >= sector_lower.get(sector, 0) - 1e-5
```

This shows that the weights have indeed been optimised to respect sector bounds:

```
utility 0.01
energy 0.1865611013277024
retail 0.1892551940539936
tech 0.2
airline 0.01
fig 0.02
```

Compared to previous:

```
utility 0.0
energy 0.1886078326102974
retail 0.1879980504951598
tech 0.2418722952745388
airline 0.0
fig 0.0
```
Note, however, that this currently does not work for `max_sharpe` because it messes up the variable substitution. But it works for `efficient_risk` and `efficient_return`. 

@schneiderfelipe do you have any opinions on whether I should build this into the main package?

**Comment by schneiderfelipe** [comment]
@robertmartin8 That's awesome! Not only very useful for the given case, but also extremely general. I think it is a nice addition, specially if things get fixed with `max_sharpe`. What's the problem there?

**Comment by robertmartin8** [comment]
@schneiderfelipe 

Essentially, maximising the Sharpe ratio requires you to make an unintuitive substitution to make it convex (see [here](http://yetanothermathprogrammingconsultant.blogspot.com/2016/08/portfolio-optimization-maximize-sharpe.html)). This part is fine, and actually I have been able to formulate the problem in cvxpy:

```python
y = cp.Variable(n)
k = cp.Variable()
risk_free_rate=0
variance = cp.quad_form(y, S.values)
constraints = [(mu.values - risk_free_rate).T * y == 1, 
               cp.sum(y) == k,
               k >= 0,
               y >= 0,
              ]

for sector in sector_upper:
    is_sector = [v == sector for k,v in sector_mapper.items()]
    constraints.append(cp.sum(y[is_sector]) <= sector_upper[sector] * k)
for sector in sector_lower:
    is_sector = [v == sector for k,v in sector_mapper.items()]
    constraints.append(cp.sum(y[is_sector]) >= sector_lower[sector] * k)

opt = cp.Problem(cp.Minimize(variance),
                constraints)
opt.solve()
w = y.value / k.value
weights = dict(zip(tickers, w))
```

Unfortunately, the reason why it's hard to translate this into pypfopt is much deeper. I have opened a new issue to discuss, because it applies to many other types of constraints.
