### ISSUE TITLE
how to use HRP with predicted returns

### ISSUE THREAD

**Issue by kchima** [robertmartin8/PyPortfolioOpt#111]
**What are you trying to do?*
Use predicted returns with HRP to manage portfolio and take advantage of clustering. With Efficient Frontier, I can just take my predicted prices for the next day and sub them in for the "mean historical return" to get my predictions (side-note, are there any problems with that approach?), but with HRP, it probably requires the full returns to cluster, but also uses the returns to generate the portfolio, rather than my predicted prices, right?

**What data are you using?**
~20 High market-cap stocks, for now, closing price data.

**Comment by robertmartin8** [comment]
Hello @kchima,

Thanks for reaching out! Your method for incorporating predicted returns is correct. The only caveat I would add is that it's really worth thinking about whether you believe that the mean of past returns is a good predictor of future returns. As I mention in the docs, my personal view is that this is rarely going to be the case, in which case you are better off optimising purely for min variance. 

As for HRP, it only requires historical returns, in order to estimate the covariance matrix. As of v1.2.1, I've [modified the API](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimisers.html#pypfopt.hierarchical_portfolio.HRPOpt) so you don't need to pass in any historical returns: you can directly pass your covariance matrix. You are correct that HRP ignores your predicted returns: HRP is essentially an advanced/improved version of minimum variance which takes into account the hierarchical structure of financial correlations.

If you want to include expected returns within the hierarchical framework, you might want to check out the mlfinlab library, built by my friends at Hudson and Thames. In particular, their [Hierarchical Clustering Asset Allocation](https://mlfinlab.readthedocs.io/en/latest/portfolio_optimisation/hierarchical_clustering_asset_allocation.html).

Hope that helps! Do leave a star if you've found it useful.

Best,
Robert

**Comment by kchima** [comment]
So I understand that mean of past returns isn't necessarily a good predictor of future returns, which is why I'm using a totally separate algorithm to predict the returns for the following day for MPT, _instead_ of the mean of historical returns which is generally what gets passed in, right?

Now I want to do the same for HRP, but it works a little differently. It would be nice if I could pass in the covariance matrix to establish the clustering, and then use that in conjunction with  predicted returns to determine the allocation.

I will check out that library you mentioned!

I left a star, this project is incredibly helpful and that was a super fast response time! You're almost at 1000, congrats!

**Comment by robertmartin8** [comment]
Yep, you're spot on.

I think HCAA is perfect for your use case: once the covariance matrix has been clustered, HCAA walks down the tree and allocates weight to each cluster based on the Sharpe ratio. 

Thanks for the kind words, I'm happy to help!
