### ISSUE TITLE
constraint for number of stock in portfolio

### ISSUE THREAD

**Issue by RazHadas** [robertmartin8/PyPortfolioOpt#113]
I really like PyPortfolioOpt amazing job.
Can give first data frame of 500 assets but I want the optimization will give me minimum variance portfolio for maximum 10 assets portfolio.
How can I make this  constraint?

Thank you in advance.

**Comment by robertmartin8** [comment]
Hi @RazHadas,

Unfortunately, that's not possible because the constraint is not convex. The issue has been touched in in #45 and #101, you could try some of the things suggested there. My view is that asset allocation is a very different problem to asset selection, and that portfolio optimisation should not be used to decide which assets should be included. Instead, my suggestion is to reduce the universe to 20-50 assets (e.g using fundamental/technical screens) then run the optimiser on that.

Hope this helps!
Robert
