### ISSUE TITLE
Optimise portfolio with target volatility

### ISSUE THREAD

**Issue by mkeds** [robertmartin8/PyPortfolioOpt#116]
Hi! Thanks for all the great work, I am following this one since `0.5.4` and I am a big fan, hence I decided to contribute.

Since the `cvxpy` update `efficient_risk` either does not work as intended, or the intention on how it should work is formulated wrongly. 

It does not give you an efficient frontier portfolio on target risk, because of line 271:
`self._constraints.append(variance <= target_volatility ** 2)`
so the solver will not enforce risk equal to target, but (obviously) lower or equal. 

On the other hand, the docs give us:
`:raises ValueError: if no portfolio can be found with volatility equal to ``target_volatility`` ` 
which is not true anymore I believe, but lead the user to expect the target volatility will be reached, or an error will be shown.

This does not happen if you request any volatility that is higher than that of the max Sharpe portfolio. And it is useful to have it for all the people that don't have access to leverage but want riskier, yet efficient, portfolios.

Now, I know going around it with cvxpy will be a hassle (I tried and unfortunately it is not DCP-enough for it...) but maybe you would consider either of:
 - reverting back to SLSQP for it (works like a charm!)
 - spending some time on DCPing it (I've spent a day and I am fed up but I believe there could be some magicians that could figure something out)
 - finally, specifying the docstring correclty (i.e. 'Maximise return for a target risk or lower.')

Anyway, happy to hear your thoughts if you can spare a moment.

Cheers, M

**Comment by robertmartin8** [comment]
Hi @mkeds,

Thanks for reaching out, and for the investigative work you have done! Let me share my thoughts on why it was built this way, and please do respond with your views/disagreements.

In fact, even when I designed the SLSQP version, I had always intended to have the `variance <= target_variance` constraint – I just couldn't get it to work for SLSQP. The reason for this is that I couldn't think of any reason why someone would take a portfolio with more risk, given the same level of return. You make an interesting point about leverage – but I still don't see why someone would want a portfolio with 20% returns and 25% vol vs 20% returns and 22% vol. So I interpret "efficient risk" as the portfolio with maximum return for a given risk tolerance. If your risk tolerance is 25%, surely you'd be happy with a portfolio with 22% vol (provided returns are the same). Let me know if there's something I'm missing here.

A secondary reason is that it allows optimisation to go ahead even when the user specifies a target volatility that is too high. For example, if we had two independent assets with volatilities 20% and 30%, then any target above 30% wouldn't work with an equality constraint.

But you are definitely correct that the docstring is incorrect, I will make a change to that.

**Comment by mkeds** [comment]
Hi Robert, thanks for the quick response.

>  ...I couldn't think of any reason why someone would take a portfolio
with more risk, given the same level of return.

The root of the problem is that returns are hardly predictable, whereas
returns squared, variance, volatility and the bunch - are (much moreso, at
least).
One can look for analytical proof (it can be shown that the percentage
error in the estimate of variance shall be smaller that in the case of
expected return estimation) and empirical, too (wide number of assets
variances exhibit high autocorrelation, unlike asset returns.

Armed with that knowledge, I would like to believe an informed investor
will place more stress on getting the volatility in line with their
requirements, rather than returns, because he/she will have more confidence
in that estimate.

Anyhow, I believe that both approaches are useful as long as they are
correctly annotated. One can imagine a soft target approach, like currently
implemented, and a hard target, forcing the volatility to be equal to
target, and so on, but I leave that to you as the author and growing BDFL
for this project :)

Thanks, Mike



pt., 15 maj 2020 o 04:41 Robert Martin <notifications@github.com>
napisał(a):

**Comment by robertmartin8** [comment]
Hi Mike,

Completely agreed about the uninformative nature of returns, which is why I always recommend users to use `min_volatility` and HRP over `max_sharpe`. 

> I would like to believe an informed investor will place more stress on getting the volatility in line with their requirements

I agree with this, and have consequentially put a lot more effort into risk models (exponential cov, Ledoit-Wolf shrinkage) than returns models, but I don't understand why an investor (everything else held equal) would want a portfolio with more volatility rather than less. 

The only reason why you could want a riskier portfolio is to have higher returns – but now we're in the domain of specifying expected returns again (which I think we agree is quite a difficult problem). An interesting compromise is the Black-Litterman model, which computes equilibrium returns based on the market's risk aversion level. 

I think it would be nice to offer the hard target approach as an option (this was also requested in #110), but I couldn't get the DCP to work either 😂 

Very much enjoying the discussion, let me know what you think!

Robert

**Comment by mkeds** [comment]
> but I don't understand why an investor (everything else held equal) would want a portfolio with ? more volatility rather than less.

I think because:

> The only reason why you could want a riskier portfolio is to have higher returns

Thus far we are in agreement :) But then you say:

> but now we're in the domain of specifying expected returns again

and I say not necessarily. I say that a prudent investor who has a strict volatility target and is confident about their volatility predictions will optimise the portfolio to the risk level they are comfortable with and then, conditional on achieving the risk target, will try to maximise expected returns as sort of a tier 2 objective, less important, but still. Just that. 

I wouldn't drag BL into this because it introduces another level of subjectivity to the portfolio optimisation problem by specifying purely arbitrary views - different purposes, totally different animal :)

You know, in any case, I don't want to imply that something is wrong methodically or conceptually with your approach -  I think its absolutely fine, besides, I am a firm believer in freedom to create. However the below bits:
1. `self._constraints.append(variance <= target_volatility ** 2)` and
2. `raises ValueError: if no portfolio can be found with volatility equal to ``target_volatility`` `
are just factually wrong in the current implementation and beg even just a sentence of explanation in the docs (1.) or a deletion (2.). 

If you were to entertain the hard target idea I can put together some time an SLSQP implementation, but I feel you wouldn't like it as I can see the whole package is all for cvxpy lately ;)

> Very much enjoying the discussion, let me know what you think!

Likewise!

-M

**Comment by robertmartin8** [comment]
> I say not necessarily. I say that a prudent investor who has a strict volatility target and is confident about their volatility predictions will optimise the portfolio to the risk level they are comfortable with and then, conditional on achieving the risk target, will try to maximise expected returns as sort of a tier 2 objective, less important, but still.

I see what you're saying - but this implicitly makes the (very fair) assumption that volatility and return are correlated, so you are still making an assumption about the distribution of future returns. Though I'm in complete agreement that this is nowhere near as heinous as using mean historical returns.

> I wouldn't drag BL into this because it introduces another level of subjectivity to the portfolio optimisation problem by specifying purely arbitrary views - different purposes, totally different animal :)

So for BL I was thinking of using it _without_ specifying views, i.e just using its equilibrium expected returns. The BL equilibrium returns quantify the relationship between risk and return (the assumption that you would otherwise be making implicitly in a volatility targeting approach), so you could use that as input to an efficient frontier optimiser. Just because of the way that BL equilibrium returns are computed, I would suspect that even an inequality constraint on the volatility would result in your target volatility being matched. 

>You know, in any case, I don't want to imply that something is wrong methodically or conceptually with your approach

You're definitely right! The current documentation is incorrect, I'll push a fix shortly.

>If you were to entertain the hard target idea I can put together some time an SLSQP implementation, but I feel you wouldn't like it as I can see the whole package is all for cvxpy lately ;)

I've been thinking about the actual problem some more. In the unconstrained setting, we are essentially trying to solve `w' S w = vol` for `w`, where `S` is the covariance matrix. The reason why this is not DCP (I think) is that there is a problem of dimensionality. If you write out the matrix multiplication in the two-asset case, the result is an ellipse in weight-space, so I don't know how the convex optimiser would choose which point on the ellipse to return. The problem is the same in higher dimensions, in which the set of all possible portfolios is a hyper-ellipsoid. In other words, there isn't a unique weight vector that corresponds to a particular volatility. The real question is what on earth SLSQP is doing to return a unique answer  - is it just ignoring the existence of other portfolios? 

Of course, if you just want _a_ portfolio with a target volatility and don't care which one, then my suggestion of passing a dummy vector of expected returns (e.g all set to 1) should work just fine.

@schneiderfelipe if you have any comments on the linear algebra it'd be much appreciated. 

 Robert

**Comment by schneiderfelipe** [comment]
> I've been thinking about the actual problem some more. In the unconstrained setting, we are essentially trying to solve `w' S w = vol` for `w`, where `S` is the covariance matrix. The reason why this is not DCP (I think) is that there is a problem of dimensionality. If you write out the matrix multiplication in the two-asset case, the result is an ellipse in weight-space, so I don't know how the convex optimiser would choose which point on the ellipse to return. The problem is the same in higher dimensions, in which the set of all possible portfolios is a hyper-ellipsoid. In other words, there isn't a unique weight vector that corresponds to a particular volatility. The real question is what on earth SLSQP is doing to return a unique answer - is it just ignoring the existence of other portfolios?

That's interesting. By assuming no asset is riskless (meaning `S` has all positive eigenvalues) and writing `w` as a linear combination of the eigenvectors of `S`, we can see that the largest and smallest values we can have for `vol` are the largest and smallest eigenvalues of `S`. Those can be found uniquely.

Any other solution would have to satisfy the constraint that the sum of the weights equal one. As such, we could equivalently minimize the Lagrangian `L = (w' S w - vol)^2 - lambda (|w| - 1)` (where `|w|` is the one-norm, i.e., the sum of components. The derivative of `L` w.r.t. the ith component of `w` is `4 (w' S w - vol) * (sum over k of S_kj * w_j) - lambda w_i`. This is non-linear and certainly has several solutions, as you pointed out.

As a numerical example,

```python3
import numpy as np
from scipy.optimize import minimize

S = np.random.rand(3, 3)
S = S.T + S  # symmetric
sigma, U = np.linalg.eigh(S)
S = U @ np.diag(sigma - sigma[0] + np.random.rand()) @ U.T  # positive-definite

vol = np.linalg.eigvalsh(S)[0] + np.random.rand()

solutions = set()
for i in range(100):
    x0 = np.random.rand(3)
    x0 = x0 / np.sum(x0)
    res = minimize(lambda w: (w @ S @ w - vol)**2, x0=x0,
                   constraints=[{"type": "eq", "fun": lambda w: np.sum(w) - 1}],
                   bounds=[(0, 1)] * len(x0))
    print(res)
    if res.success and np.isclose(res.x @ S @ res.x, vol, rtol=1e-1):
        solutions.add(tuple(res.x.round(2)))
        print(f"w' S w = {res.x @ S @ res.x}")

print(f"{len(solutions)} solutions found")
```

If you get a single solution out of the above, you're lucky :) (Sometimes, the solver gets stuck, and no solution is found. I found this to be more likely than finding a single solution. [`basinhopping`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.basinhopping.html) might help, but this shows how rough is the surface we're minimizing on.)

**Comment by robertmartin8** [comment]
@schneiderfelipe Thanks for the fantastic work! I forgot about the weight constraint – in the geometric picture, this corresponds to a hyperplane. The intersection between a hyperplane and a hypersphere will still be a hypersphere with one less dimension (unless you're lucky and it's a tangent plane). 

@mkeds I think the conclusion of all this is that the problem of finding a portfolio with a given target risk is mathematically ill-formed.

**Comment by mkeds** [comment]
@schneiderfelipe @robertmartin8 great discussion, thanks!

I concur that it is (probably) ill-formed but let me, for the sake of argument, have a go at it from another side. Here goes:
EXCEL's Solver can solve it with no hiccups! 😄 
Can we be beaten by such layman's tool? I think not!

@schneiderfelipe I think in your code the solver would very much benefit from adding the return objective - this way if there are several `w` s.t. `wSw' = vol` the solver will have something to fall back on to differentiate between them.

In my applications I structured the objective function in such a way that it minimises the negative return, minimises the difference between the volatility and volatility target, and also minimises the difference between sum of `w` and one - all of the above at the same time, as a weighted sum of objectives. Moreover, I specified the constraints s.t. sum of `w` is <0,1> and volatility is in some small range around the volatility target. Formulated like that SLSQP converges quickly and with sensible results.

However, for some more advanced exercise involving the topic of style analysis I had to employ a global solver and since then I am doubting whether the SLSQP in the former case indeed finds a global minimum or just a local one. 

Does any one of you have any thoughts about the smoothness and monotonicity of the objective function I just specified? Because if it is both, we can be sure we can use SLSQP and get the actual optimum. It would be easy to implement using @schneiderfelipe's code with minor tweaks and @robertmartin8 would hopefully not be bothered too much about using something different than cvxpy in this special case. 

If it is not, then I would recommend differential evolution (I used it extensively because with some tweaks it works well with integerized inputs like share numbers) or perhaps basinhopping.

**Comment by robertmartin8** [comment]
@mkeds 

I suppose what I'm trying to ask is _which_ portfolio (of all the possible portfolios that meet your volatility target) you would like the function to return. Because if you're not picky, a cvxpy solution is to run `efficient_risk` with a dummy return vector.

Regarding your optimisation problem, is there a reason why you've relaxed the weight constraint? scipy lets you put in hard constraints rather than incorporating them into the objective function. 

I'm hesitant to support any `scipy.optimize` implementations (outside of the singular `ef.nonconvex_objective()`, just because it doesn't at all play nicely with the current API for specifying constraints.

**Comment by schneiderfelipe** [comment]
@mkeds, very interesting points.

1. Among all portfolios with the same specified risk, there is a *single* one with the highest return. It happens to be the one with the highest Sharpe ratio. In other words: minimizing the Sharpe ratio subject to a specified risk constraint is an equivalent problem to getting the portfolio with maximum return among all of the specified risk. You get the same result.
2. If you minimize the Sharpe ratio subject to a *maximum* risk constraint, you might be lucky to find a less risky portfolio. Increasing the risk here wouldn't give you the same reward. But allowing `<=` to become `==` in `efficient_risk` will give you what you want.

@robertmartin8, a `strict=True` option for `efficient_risk` could be an alternative. I believe this should still be convex. That would ensure the user gets the risk he/she specified.

**Comment by robertmartin8** [comment]
@schneiderfelipe 

The problem here is that the strict version is not DCP. This works:

```python
w = cp.Variable(len(mu))
ret = mu.values.T*w 
prob = cp.Problem(cp.Maximize(ret), 
               [cp.sum(w) == 1, 
                cp.quad_form(w, S) <= 0.19])
prob.solve()
```

This doesn't:

```python
w = cp.Variable(len(mu))
ret = mu.values.T*w 
prob = cp.Problem(cp.Maximize(ret), 
               [cp.sum(w) == 1, 
                cp.quad_form(w, S) == 0.19])
prob.solve()
```

I agree with your point 1 and 2, but based on my reading of the question @mkeds wants to construct a portfolio with a target volatility without specifying returns, so `efficient_risk` won't work here.

**Comment by schneiderfelipe** [comment]
@robertmartin8  I see. Well, then either dummy returns or `nonconvex_objective` already provide the required functionality?

As a second thought, sticking with `<=` and checking if the requested maximum risk matches the portfolio risk also works. This will be true whenever the requested maximum risk is less than or equal to the market Sharpe ratio, or am I missing something here? If it is larger, there is a better opportunity in the capital market line anyway... (I'm going beyond math now and I am no economist, so this should be taken with a grain of salt).

**Comment by robertmartin8** [comment]
@schneiderfelipe I think your description is correct.

In practical terms, this means that for reasonably low values of `target_risk`, the distinction between `<=` and `==` doesn't really matter. You only start seeing deviations when you use large `target_risk` values.

**Comment by mkeds** [comment]
> Regarding your optimisation problem, is there a reason why you've relaxed the weight constraint? scipy lets you put in hard constraints rather than incorporating them into the objective function.

I wanted the flexibility of being able to balance being close to the vol target and return optimum vs. being fully invested. In the real-world application I am involved in, it is **desirable** to have 0% cash on portfolio, but it is **required** to achieve the volatility target albeit with some small tolerance, and it is **desirable** to achieve high estimated returns. There is no set preference between being fully invested and having 0% cash so I have to 'wiggle' around it.

> Among all portfolios with the same specified risk, there is a single one with the highest return. It happens to be the one with the highest Sharpe ratio. In other words: minimizing the Sharpe ratio subject to a specified risk constraint is an equivalent problem to getting the portfolio with maximum return among all of the specified risk. You get the same result.

This is exactly what we want to do. For some set level of risk, we want the portfolio with the highest expected return. Each word in the previous sentence taken literally, no exceptions.

> I agree with your point 1 and 2, but based on my reading of the question @mkeds wants to construct a portfolio with a target volatility without specifying returns, so efficient_risk won't work here.

This is not what I wanted to get across in the question and previous posts. I am all for specifying returns, I just think of them as a secondary objective, a 'next best thing'. We HAVE to reach the volatility target, one we have it, we CAN (and should) maximise the returns. Any other formulation of the problem boils down to:

> either dummy returns or nonconvex_objective 

:)

> sticking with <= and checking if the requested maximum risk matches the portfolio risk also works. This will be true whenever the requested maximum risk is less than or equal to the market Sharpe ratio, or am I missing something here? If it is larger, there is a better opportunity in the capital market line anyway

On the CML - yes, but what if you are constrained to the efficient frontier? 

1. Portfolio with a volatility lower than the market portfolio that lies on the CML is a market portfolio de-leveraged, effectively with some part of the funds left in cash. That is easy to implement for any market participant - just do nothing with part of the capital you have.
2. Portfolio with a volatility larger than the market portfolio that lies on the CML is a market portfolio leveraged - with some capital sourced from an outside party, borrowed. This is still hard to implement for many market participants: individual investors (behaviourally) would often not be willing to borrow to invest, small brokerage houses can have a credit score prohibiting from borrowing on good rates... real-life examples are numerous.

> In practical terms, this means that for reasonably low values of target_risk, the distinction between <= and == doesn't really matter. You only start seeing deviations when you use large target_risk values.

I think >low< and >large< terms are not precise in the above quote. I mentioned in my previous posts that the deviation will happen always when you choose `target_risk` higher than the risk of some max return portfolio because the way the objective function is formulated in the current implementation: risk is a half-open constraint and the return is the objective. 

Therefore for each portfolio "to the right" of the max return portfolio, you will get the max return portfolio - even though you don't want it. If you wanted it, you would have used `efficient_return`. But you are using `efficient_risk` and counting on getting a portfolio on a desired risk level, but consistently getting a lower one...

...and your client sues you because your investment mandate specifically says the Client wants to sustain a consisntent risk level of 10-15% and best you can do is 5%? 

_last paragraph for humorous purposes_

**Comment by robertmartin8** [comment]
@mkeds 

Thanks for the detailed response, I now have a much better understanding of what you're after (and why you're after it).

I guess the "classic finance" response is that you should use the max Sharpe portfolio then lever it up/down to the desired risk level. This is equivalent to not requiring the weights to sum to one, though I do appreciate that it's much easier to let the weights sum to less than 1 compared with leveraging up. 

> the deviation will happen always when you choose target_risk higher than the risk of some max return portfolio

I suppose my question now becomes whether this is an "edge case" or a common requirement, though it's true that it being an edge case doesn't mean it shouldn't be treated properly by PyPortfolioOpt.

My current proposal is to build a simple scipy solution (though I don't have the expertise to do anything beyond the basic `scipy.optimize`) and just slap on a tonne of warnings saying that it won't play nicely with the cvxpy constraints/objectives. What do you think?

**Comment by robertmartin8** [comment]
As of v1.2.3, I've updated the docs to briefly mention this. Leaving the issue up in case someone figures out whether there is some way of changing the variables to make this DCP.

**Comment by robertmartin8** [comment]
@phschiele This is an old issue, but you've got a great track record of finding workarounds for other thorny issues (like the cardinality constraint), so your thoughts on this would be appreciated!

**Comment by phschiele** [comment]
@robertmartin8 skimming through the issue I think the question is: can I maximize return given target volatility (`==`) rather than a volatility ceiling (`<=`). Here is my two cents:

**Intuition:**
The mean-variance framework is based on the assumptions that more return is, ceteris paribus, better, and more risk is, ceteris paribus, worse. Indeed, it would not make sense in that framework to select a portfolio with the same expected return, but higher variance. Of course, someone might target a specific volatility, so leverage would indeed be the preferred way to achieve this, as mentioned in some previous answers.

**Optimization:**
Let's say someone would nevertheless want to do just that: increase risk up to the desired level, even if the expected return does not increase further. This is saying one wants to hate a quadratic equality constraint (something like `x' Sigma x` == target_variance). Generally speaking, quadratic equality constraints are not convex. Consider `f(x)=x^2`:
the constraint `f(x)<=1` is clearly convex. However, `f(x)==1` is not convex (its just two distinct points). Convex optimization is "going down a hill", so if you have only two points, that's not possible. 

**Heuristic:** 
Potentially, one could break the return equivalence for the portfolios with the same variance. This could heuristically be done by marginally increasing the returns according to their volatility (Note: this would not consider covariances, so therefore it's a heuristic). This is just what first came to my mind, I'll think about if there are better ways to do that.

**Why can other solvers (excel, scipy) still solve it:**
A problem that is not convex can still be (attempted to be) solved. It's just that you don't have a "certificate of optimality" in most cases. CVXPY is built for convex optimization, so it will throw an exception if the problem is not convex.

**Comment by phschiele** [comment]
@robertmartin8 @schneiderfelipe Another equally interesting question, aside from why the quadratic equality constraint is not convex, is in which cases one would end up with a non-binding inequality. Generally speaking, the feasible set (of portfolios) is convex. If you pick any risk-level `sigma` such that `sigma_GMVP` < `sigma` < `sigma_max_return_pf`, one would therefore expect to be able to increase expected returns until the inequality on the risk-level is binding. I would therefore attribute scenarios where the risk level is (not-numerically) smaller than specified in `efficient_risk` to some form of ill-conditioning. 

Would be interesting to look at such a scenario. If anyone has an MWE, please share it here.
