### ISSUE TITLE
Add plot_efficient_frontier to pypfopt.efficient_frontier.EfficientFrontier

### ISSUE THREAD

**Issue by pedrovgp** [robertmartin8/PyPortfolioOpt#117]
I optimized a portfolio with ef = pypfopt.efficient_frontier.EfficientFrontier(...).
Then I tried visualizing the efficient frontier with ef.plot_efficient_frontier(), but to my surprise, it failed with: AttributeError: 'EfficientFrontier' object has no attribute 'plot_efficient_frontier'

It seems that plot_efficient_frontier is defined in CLA and EfficientFrontier does not inherit that method.

Is there an alternative way to plot the efficient frontier from an EfficientFrontier optimized object?

**Comment by robertmartin8** [comment]
Hi @pedrovgp,

Thanks for reaching out! There is no current built-in way to plot the frontier from an `EfficientFrontier` object. The reason is that I haven't figured out a nice way of doing so. I think the standard way is to maximise the quadratic utility for different values of risk aversion, so it would be something like:

```python
ef = EfficientFrontier(mu, S)
rets = []
stds = []
for risk_aversion in np.arange(0, 2, 0.05):
    ef.max_quadratic_utility(risk_aversion)
    ret, sigma, _ = ef.portfolio_performance()
    rets.append(ret)
    std.append(sigma)

plt.plot(stds, rets)
```

The problem is that because a cvxpy object is immutable, this would mess up the `ef` object that you pass to the plotting method. I guess I could try to create a deep copy first, but I haven't figured out if this is the best way of doing it.

Best,
Robert

**Comment by pedrovgp** [comment]
Thanks for the quick answer and snippet!
