### ISSUE TITLE
PyPI requires pandas <0.26, deps missing scikit-learn and matplotlib

### ISSUE THREAD

**Issue by jkleint** [robertmartin8/PyPortfolioOpt#118]
Thanks for such a great project.

I ran into some issues trying to install PyPortfolioOpt from PyPI with pip.  Although I can't find this requirement anywhere in the code, it seems that the [PyPI metadata](https://pypi.org/pypi/pyportfolioopt/json) specifies a `requires_dist` of `pandas (>=0.25.3,<0.26.0)`.  This prevents me from installing PyPortfolioOpt with Pandas 1.0.  

Also, it seems that scikit-learn and matplotlib are not listed in setup.py, but are required to import pypfopt.  There are a few other packages in requirements.txt that don't show up in setup.py.

Python packaging is kind of a mess, and I know you use poetry, but perhaps there's some way to automatically export poetry's dependency requirements and stuff them into setup.py as part of build?
That way the requirements don't drift out of date.

**Comment by robertmartin8** [comment]
Hi @jkleint,

Thanks for raising this! It's normally quite hard for me to know what's working on other people's machines, so I appreciate it.

It's strange because currently in my `setup.py` I only say `pandas`, so I don't know where PyPI is getting the `<0.26.0` (given that both my `requirementx.txt` and `pyproject.toml` only say `>=0.5.3`).

sklearn and matplotlib were excluded by design: I wanted them to be "optional" imports, but I think in the case of matplotlib I might have messed up, because I imported the `plotting` module (which requires matplotlib) in the `__init__.py`. Not sure what's going on with sklearn though, it shouldn't be required..

Python packaging is indeed a nightmare, I find myself having to manually copy stuff from the poetry spec file to both `requirements.txt` and `setup.py`. Hopefully #119 fixes it.

Cheers,
Robert

**Comment by jkleint** [comment]
Hey Robert, thanks for such a quick response!

Sadly, it didn't fix the problem.  :(  The  PyPI metadata still has a `requires_dist` of `pandas (>=0.25.3,<0.26.0)`.  

Quoth PyPI:
> Project description and sidebar
> 
> To set the <project> description, author, links, classifiers, and other details for your next release, use the setup() arguments in your setup.py file. Updating these fields will not change the metadata for past releases. Additionally, you must use Twine to upload your files in order to get full support for these fields. See the Python Packaging User Guide for more help. 

I'm guessing you use poetry to upload to PyPI, so maybe it's a poetry bug?  Are you on the latest poetry?

I've seen this script suggested to generate setup.py automatically from pyproject.toml:
https://github.com/sdss/flicamera/blob/master/create_setup.py

Also, for reasons that aren't entirely clear to me, the Python Packaging User Guide discourages pinning versions at all in setup.py:
https://packaging.python.org/discussions/install-requires-vs-requirements/

Docker is a great way to see what us mere mortals experience when installing.  Here's a super simple Dockerfile to reproduce the problem:
```
FROM python:3.8

CMD pip install pyportfolioopt && python -c 'import pypfopt'
```
(Of course you can `pip install` from a git commit instead of PyPI for testing.  :) )

Some highlights:
```
Collecting pandas<0.26.0,>=0.25.3
  Downloading pandas-0.25.3-cp38-cp38-manylinux1_x86_64.whl (10.4 MB)
```

The scikit dependency is coming from `risk_models.CovarianceShrinkage`:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pypfopt/risk_models.py", line 367, in CovarianceShrinkage
    import sklearn.covariance
ModuleNotFoundError: No module named 'sklearn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pypfopt/__init__.py", line 9, in <module>
    from .hierarchical_portfolio import HRPOpt
  File "/usr/local/lib/python3.8/site-packages/pypfopt/hierarchical_portfolio.py", line 21, in <module>
    from . import base_optimizer, risk_models
  File "/usr/local/lib/python3.8/site-packages/pypfopt/risk_models.py", line 351, in <module>
    class CovarianceShrinkage:
  File "/usr/local/lib/python3.8/site-packages/pypfopt/risk_models.py", line 369, in CovarianceShrinkage
    raise ImportError("Please install scikit-learn via pip or poetry")
ImportError: Please install scikit-learn via pip or poetry
ry
```

I didn't mean to make you include matplotlib as a required dependency, I also prefer it being optional if we can figure out how to only import it on use.

Thanks again for your help on this one!

**Comment by robertmartin8** [comment]
Thanks for the investigative work! Really appreciate it.

I think I need to spend some time reading what `poetry build` and `poetry publish` are actually doing. Currently, I have both a `pyproject.toml` and a `setup.py`. I only updated the `setup.py` for the latest push, so `pyproject.toml` still says `pandas = "^0.25.3"`. I wonder whether the issue is caused by poetry automatically inferring that I want `0.25.3<=x<=0.26`, and `poetry build` ignoring my current `setup.py` to make its own. 

As for sklearn, I'm stupid. The `__init__.py` said `from risk_models import CovarianceShrinkage`, and my `risk_models.py` file had the line:

```python
class CovarianceShrinkage:
       try:
            import sklearn.covariance
        except (ModuleNotFoundError, ImportError):
            raise ImportError("Please install scikit-learn via pip or poetry")

    def __init__(self):
        ...
```

So `__init__.py` is causing the `import matplotlib` statement to run. I _think_ that moving the try/except block into the class constructor solves this problem, because then the block won't be run until a user instantiates the class. 

As for matplotlib, I would also like to keep it optional but the trouble is that all the plotting functions are static functions within `plotting.Plotting`. One solution could be to define another static method `check_import()` which tries to import matplotlib, then each static plotting function e.g `plot_covariance()` will first call `check_import()`. 

I'll have to do a bit of digging into poetry to see exactly how it converts requirements to PyPI's format. Good call on docker, will run some experiments!

Best,
Robert

**Comment by KikeM** [comment]
Hi @robertmartin8 

Really good work, thank you!

Regarding your observation 

> Thanks for raising this! It's normally quite hard for me to know what's working on other people's machines, so I appreciate it.

I have seen that you are already using Travis, but you install the library with the `-r requirements.txt` command, which is not what will happen when the library is installed via pip as a dependency of another library. I think with an small effort in the Travis setup file you will be able to keep track of the correct functioning of the library across platforms and installation procedures. 

I'll have a look and probably create a PR.

**Comment by robertmartin8** [comment]
@KikeM 

Thanks for the suggestion! I'm not super knowledgeable regarding the whole packaging/environment thing, so your input is valuable.

But I think if we take out the `pip install -r requirements.txt`, the tests that require optional dependencies will fail.

Probably the best way forward is for me to try installing the package in a virtualenv after every update to make sure it works (or to do it in a docker container). What do you think?

Robert

**Comment by jkleint** [comment]
Travis runs on every commit, and you want to be able to test changes before releasing to PyPI (that's kind of the point!).  You could imagine a separate Travis task that only runs for releases, but at that point it's a little too late -- you've already released code to the world.  

It may be worthwhile to think about automating releases, but since it's relatively infrequent it may not be worth it.  A simple checklist, including installing in a venv or docker, may suffice.  Of note is https://test.pypi.org/, which exists precisely to address this problem.  You can publish to it and then install from it without affecting the Real World(TM).

**Comment by jkleint** [comment]
As for the matplotlib dependency, it seems to be an artifact of the static class design of the plotting module.  Can you explain a little why you went with that design?  A class full of only static methods, that you never instantiate, is a bit of a code smell in Python.  Does that buy you anything over just putting functions in a module?  In other words, instead of 
```
from pypfopt import Plotting  # The class
Plotting.plot_xxx()
```

why not just
```
from pypfopt import plotting  # The module
plotting.plot_xxx()
```

That way, you only import the module (and matplotlib) if you, well, import the module.  :)

**Comment by robertmartin8** [comment]
@jkleint 

I used `test.pypi.org` in the early days, but I guess I got a bit sloppy and stopped bothering. Will start using it again I reckon :)

As for the design choice of plotting, I'm very confused now. Because I see that you are correct, and in fact for all of PyPortfolioOpt I've emphasised modules over classes (e.g `risk_models` and `expected_returns`), so I'm really struggling to remember why I put it in a class. I think I was reading another library's code and saw that pattern so was subconsciously influenced 😂 

I'll give it a couple of days to think about whether I had some reason, but as you point out, it doesn't structurally make sense, apart from using it as a method to group similar methods (which is redundant because they are in a model).

**Comment by robertmartin8** [comment]
It turns out that the issue was from my use of `poetry`: I initially had `pandas=^0.25.3` but didn't realise that poetry assumes you don't want to go to a new major version. Changing it to `pandas >= 0.19` fixed it. 

I also made the change to the `plotting` library, hopefully it's not a major inconvenience to people.

Release 1.2.3 was tested on `test.pypi.org` so I am reasonably confident it works as intended, but do let me know if you have any issues!

**Comment by jkleint** [comment]
Nice, works for me!  Thanks again.
