### ISSUE TITLE
Version update - zipline integration.

### ISSUE THREAD

**Issue by andrewcz** [robertmartin8/PyPortfolioOpt#12]
@robertmartin8 hey!
Was wondering if zipline was being added to the library.
Looks very promising :)!!
I wanted to try it out with some backtests.
Best,
Andrew

**Comment by robertmartin8** [comment]
Hi Andrew,

This is definitely something that I had always been meaning to build (though possibly with [backtrader](https://www.backtrader.com/) rather than Zipline). In fact, when I was working on portfolio optimisation professionally, I did actually have a go at doing a zipline/backtrader backtest, but in the end our team came to the conclusion that event-driven backtesting frameworks are not really suitable for backtesting portfolio optimisation methods, or at least they are certainly not worth the development effort. Here are a couple of interesting discussions on the topic ([quantstart](https://www.quantstart.com/articles/Event-Driven-Backtesting-with-Python-Part-I), [quantopian](https://blog.quantopian.com/when-should-you-build-your-own-backtester-by-michael-halls-moore/): I am inclined to believe that a simple for-loop backtest is superior in our case.

Unfortunately, university commitments mean that I will not be able to tackle this. However, I may considering uploading my for-loop backtesting script instead, but I will need to make heavy modifications before it is ready for distribution. 

Best,
Robert

**Comment by andrewcz** [comment]
Champion! Interesting thoughts. 
Would you be able to include fees and slippage?
I was looking at a couple of basic for loop backtests but I would question the reality of the modeling?
Best,
Andrew
