### ISSUE TITLE
With negative weights allowed, does efficient frontier assume infinite leverage?

### ISSUE THREAD

**Issue by kchima** [robertmartin8/PyPortfolioOpt#133]
**What are you trying to do?**

I am trying to incorporate short-sells into my portfolio, which previously just used Longs.

**What data are you using?**
~20 large market cap stocks from the SP500.

So it makes some amount of sense that once I allowed negative weights, and still had "weights_sum_to_one" True, the abs weights would sum to more than 1. To me, this means that the portfolio assumes we have some amount of margin/leverage, in order to be able to do shorts, correct? What assumptions does it make about the amount of leverage available to us / how does it arrive at what weights are optimal? Is there a way to change how much leverage / margin it assumes is available to us?

**Comment by robertmartin8** [comment]
Hi @kchima,

This is an excellent question and I have certainly grappled with it myself (see also #94). Currently, the portfolio _allows_ infinite leverage even with weights summing to one, because of what you mentioned. However, in practice, the optimiser never chooses to use all of this leverage because doing so incurs a "cost" in terms of risk. If you borrow 100% of weights to buy asset A, although you reap the benefits of anticorrelation, you do still incur the entire volatility cost. Of course, it is easy to construct a simple example that blows up, e.g if you tried to maximise return directly without considering risk. 

Currently, there are two solutions to enforce a given level of leverage:

1) Make abs weights sum to one then rescale, e.g `w = 1.3 * w / w.sum()` for 30% leverage. 
2) Handle leverage constraints on the allocation side as opposed to the optimisation side. The [`DiscreteAllocation` class](https://pyportfolioopt.readthedocs.io/en/latest/Postprocessing.html#pypfopt.discrete_allocation.DiscreteAllocation.__init__) converts weights to actual numbers of shares and lets you pass a `short_ratio` in the initialiser. 

Neither is ideal because it conceptually makes more sense for this to be on the optimisation side since it is indeed a constraint. But I haven't been able to formulate it in a manner that works with the convex optimisation backend; specifically, a constraint of the form `cp.norm(w, 1) <= 1.3` does not seem to satisfy DCP rules. If anyone has a fix I'm all ears.

Best,
Robert

**Comment by kchima** [comment]
Thanks Robert! That is very helpful. I'm eager to dip my toe into the discrete allocation bit bc I've just been doing it manually so far.

**Comment by robertmartin8** [comment]
@kchima 

Could you give me an example of the DCP error?

This works for me:

```python
ef = EfficientFrontier(mu, S, weight_bounds=(None, None))
ef.add_constraint(lambda w: cp.norm(w, 1) <= 1.3)
ef.min_volatility()
```

**Comment by kchima** [comment]
Sorry I missed this, I don't think I have encountered any error, just had the original question, which you've answered. I am noting down your example, as I think this will work very well for my purposes. Thanks!

**Comment by Spichon** [comment]
Hi Robert,

I've been struggling within the same issue for days. Your solution about rescaling is a nice workaround through.
A solution about your optimization could be to add the following contraints (for a 0.3 short ratio) : 

- A leveraged bounds on each long position to lie between 0 and 1.3 (Wk+)
- A bounds on each short position to lie between 0 and -0.3 (Wk-)

Also, I've found a nice post from a indian researcher using genetic algorithms.
I let you check : https://github.com/PaiViji/PythonFinance--130-30-Portfolio-Construction/blob/master/MainContent.ipynb

Regards,
Simon

**Comment by michaelmech** [comment]
You could softmax the portfolio weights, and put their original signs back.

**Comment by robertmartin8** [comment]
@michaelmech I'm not too clued up on the properties of the softmax function; I wonder if this preserves the optimality of the portfolio allocation?

**Comment by michaelmech** [comment]
Or more simply,  just divide all the weights by the absolute sum. The weights retain their relative sizes to one another, while now, absolute-summing to 1.

**Comment by nathanramoscfa** [comment]
> 

When I use this constraint, it generates a 115/15 portfolio. I changed the constraint from:

`ef.add_constraint(lambda w: cp.norm(w, 1) <= 1.3)`

to

`ef.add_constraint(lambda w: cp.norm(w, 1) <= 1.6)`

And got the expected 130/30 long/short portfolio. Is this the expected behavior? Why would I need to set it to 1.6 to get a 130/30 long/short portfolio? 

Here is my code: 

```
max_sharpe_results = pd.DataFrame()
ef = efficient_frontier.EfficientFrontier(posterior_exp_returns, posterior_cov_matrix, bounds)
ef.add_objective(objective_functions.L2_reg, gamma=gamma)
ef.add_constraint(lambda w: cp.norm(w, 1) <= 1.6)
ef.max_sharpe(risk_free_rate=risk_free_rate)

max_sharpe_performance = pd.DataFrame(ef.portfolio_performance(risk_free_rate=risk_free_rate)).round(4)
max_sharpe_results = pd.concat([max_sharpe_results, max_sharpe_performance], axis=1)
max_sharpe_results.columns = ['PORTFOLIO']
max_sharpe_results = max_sharpe_results.rename(index={0: 'Expected_Return', 1: 'Volatility', 2: 'Sharpe_Ratio'})

max_sharpe_weights = ef.clean_weights(min_weight)
max_sharpe_weights = pd.DataFrame.from_dict(max_sharpe_weights, orient='index', columns=['Optimal Portfolio']).round(4)
max_sharpe_weights = clean_weights(max_sharpe_weights, cutoff=min_weight)
max_sharpe_weights.index.name = 'TICKER'
max_sharpe_weights = max_sharpe_weights.fillna(0)
max_sharpe_weights.squeeze().sort_values(ascending=False)
```

Output:
Portfolio Weights:
```
TICKER
QQQ     0.621893
PSCD    0.201740
VIOG    0.199565
VIOV    0.164561
SPSM    0.106980
FYX     0.000000
XLU     0.000000
XME     0.000000
SPYV   -0.103148
OIH    -0.191591
Name: Optimal Portfolio, dtype: float64
```

**Comment by aconstandinou** [comment]
@nathanramoscfa 

hey - I know this chain is a bit old but I'm wondering if perhaps the input parameters for the constraint is total gross exposure (130% long and 30% short is a total 160% gross exposure)

wondering your thoughts

**Comment by nathanramoscfa** [comment]
> @nathanramoscfa
> 
> hey - I know this chain is a bit old but I'm wondering if perhaps the input parameters for the constraint is total gross exposure (130% long and 30% short is a total 160% gross exposure)
> 
> wondering your thoughts

It appears as though, yes, the input parameter for the constraint is gross exposure = % long + % short. I had to figure this out by trial and error. Here are some examples from my open-source [automated trading bot](https://github.com/nathanramoscfa/etradebot/blob/main/model/model.py#L334).
