### ISSUE TITLE
Different covariance plots in Python 3.7.8

### ISSUE THREAD

**Issue by sackio** [robertmartin8/PyPortfolioOpt#148]
**Describe the bug**
Running the cookbook examples using v1.2.3 on Python 3.7.8, I am getting odd covariance plots (covariance of stocks with themselves is < 0.33). 

**Screenshots**
See screenshot of the plot I get below:

![image](https://user-images.githubusercontent.com/954944/87044017-f287f000-c1c3-11ea-8fad-d8fd5ebc7c08.png)

**Operating system and python version:**
Ubuntu 16.04, Python 3.7.8, PyPortfolioOpt 1.2.3

**Comment by robertmartin8** [comment]
Hi @sackio,

Thanks for raising this! What you have shown is a feature, not a bug :wink:. The heatmap plots the covariance matrix, not the correlation matrix. So the diagonals represent the asset variances.

However, what might be causing confusion is that in a previous release, PyPortfolioOpt's `plot_covariance` function actually plotted the correlation matrix. I later fixed this because it was silly.

Incidentally, I've noticed that the docs page for the `plotting` module is currently down, so I'll try to get that back online.

Cheers,
Robert

**Comment by sackio** [comment]
thanks so much for the help -- and the package, it's fantastic
