### ISSUE TITLE
Calculation of efficient frontier and confidence boundary

### ISSUE THREAD

**Issue by joostbos123** [robertmartin8/PyPortfolioOpt#149]
Great repo and a subject I find very interesting as well! Some time ago, I created functions for portfolio optimisation that turn out to be very similar. Although, I also saw small differences about which I have the following two question: 

- Why have you chosen to calculate points on the efficient frontier by numerical optimisation instead of using the closed-form formula, that can for example be found [here](http://www.calculatinginvestor.com/2011/06/07/efficient-frontier-1/)?

- A feature which can probably be very useful is calculation of the confidence bound of the efficient frontier, also because it can be used to test if an existing portfolio is statistically efficient or not. Have you thought about adding this feature? I used bootstrap to do this myself, which seemed to work but took a lot of computation time.

Kind regards,
Joost

**Comment by robertmartin8** [comment]
Hi Joost,

Thanks for the questions! 

The reason why I am using a convex optimiser rather than the explicit matrix solution is that as soon as you add constraints or objectives, the explicit solution becomes very difficult to write down (more than one Lagrange multiplier etc).

Regarding the confidence bound on the efficient frontier, are you referring to Michaud's resampled frontier? If not, it'd be great if you could share a link to a paper or blog post so I can read more about it.

Cheers,
Robert

**Comment by joostbos123** [comment]
Hi Robert,

Thanks for your fast response and using the convex optimiser makes sense! As far as I can understand, the method I used is similar to the Michaud's resampled frontier. Thought I used [this](https://link.springer.com/article/10.1007%2Fs10287-016-0257-2) article. Would be really cool to ad that feature in my opinion!

Kind regards,
Joost

**Comment by robertmartin8** [comment]
Hi Joost, 

Thanks for the link. Let's keep the issue open so that I'm more likely to revisit it in future.

Cheers,
Robert

**Comment by robertmartin8** [comment]
I was reading about this. Unfortunately, the resampled efficient frontier algorithm is patented, so even personal usage requires licensing/authorisation. Very irritating. 

I've got my own ideas about how MVO could be improved by sampling; hopefully at some point in the future I'll have a chance to incorporate them into PyPortfolioOpt.
