### ISSUE TITLE
Queries regarding James Stein estimator implementation

### ISSUE THREAD

**Issue by bhutraaditya** [robertmartin8/PyPortfolioOpt#167]
https://github.com/robertmartin8/PyPortfolioOpt/blob/386d72da52d1ddaeb9eabb49f04e7386078ff7ea/pypfopt/expected_returns.py#L204-L209

1. Line 207 - Could someone please explain why it is permissible to use the binomial variance estimate in this scenario since `mu_bar` is not restricted between [0,1] 
Also, this implementation assumes that the variance of all timeseries in `returns` is equal which seems unrealistic

2. Line 209 - I would have expected it to be the other way around: `theta_js = (1 - kappa) * mu_bar + kappa * mu`

**Comment by robertmartin8** [comment]
Hi @bhutraaditya,

I based Line 207 off of one of the papers I read, but in retrospect, you are right that it makes little sense to use the binomial estimate. In the next update to PyPortfolioOpt, I will update this to the overall variance.

As for line 209, this is just because I have defined kappa as `1 - [...]`. 

Thanks for these questions!
Robert

**Comment by bhutraaditya** [comment]
@robertmartin8 Thanks for the quick response!

Even if we replace `sigma_squared` with the overall variance, I am still skeptical about the use of this technique here. JS estimator is used when there is "just one" observation available. In this case, we have a series of observations available and we are just using the estimator over the mean of our original set of observations and assuming that all mean vector has constant variance. Is there a rationale behind the same? 

For Line 209, could you please recheck (or point me to a good resource )  because I still think otherwise.

**Comment by robertmartin8** [comment]
@bhutraaditya 

As for line 209, I believe I based my implementation off of [this resource](https://bookdown.org/content/922/james-stein.html), which also explains my mistake with the binomial approximation. 

As for the applicability of JS, it's a good point and I'm afraid I will need to do a bit more reading. I understand that in most examples, JS refers to estimation of underlying parameters based on a single draw, but I think I read somewhere that it also works with more than one draw? (this is suggested in the previous link, as they use the average of 5 values rather than a single draw).

**Comment by bhutraaditya** [comment]
> As for line 209, I believe I based my implementation off of [this resource](https://bookdown.org/content/922/james-stein.html), which also explains my mistake with the binomial approximation.

Check 4.1.4 of the resource you mentioned. Line 209 should be `theta_js = (1 - kappa) * mu_bar + kappa * mu`
I have verified it with another resource too.
