### ISSUE TITLE
Positive semi-definite check is not correct

### ISSUE THREAD

**Issue by bhutraaditya** [robertmartin8/PyPortfolioOpt#176]
**Describe the bug**
Current implementation: `_is_positive_semidefinite` is `True` iff `np.linalg.cholesky(matrix)` executes successfully.
However, Cholesky decomposition runs successfully for all Positive-definite matrices but not necessarily for Positive semi-definite matrices.

Eg.
`np.linalg.cholesky(np.zeros((2,2))` -> Fails

**Expected behavior**
Matrices with zero eigenvalues should be treated as PSD matrices.

**Suggested solution**
`np.linalg.eigvalsh(matrix) > 0`

This is mathematically precise and transparent.

**Comment by robertmartin8** [comment]
Hi @bhutraaditya

This is a good catch. You are right that it is inaccurate to describe this method as `is_positive_semidefinite` because it is actually testing for positive-definiteness. However, checking the eigenvalues is much less efficient: [this SO thread](https://stackoverflow.com/questions/16266720/find-out-if-matrix-is-positive-definite-with-numpy) has a great discussion of the pros and cons of each.

One of the suggestions in the comments is to add a small positive perturbation before doing the Cholesky factorisation:

`np.linalg.cholesky(matrix + 1e-18 * np.eye(len(matrix))`

However, it seems that both the eigenvalue and Cholesky method are technically wrong because they assume symmetry – i.e non-symmetric matrices may "pass" the Cholesky/eigenvalue tests but may not be PD/PSD. 

Do you have any thoughts on this?
