### ISSUE TITLE
A few questions about mean variance optimization and ef.max_sharpe()

### ISSUE THREAD

**Issue by gtamba** [robertmartin8/PyPortfolioOpt#179]
Hello! First of all thanks a lot for this library it has a very nice interface and the code is a great reference to harden the loose ends on concepts I have only recently began learning. 

I did have a question about mean variance optimization, I am trying to allocate an optimal portfolio among a set of asset classes. The expected returns tend to be negative for 2 or 3 out of 5 asset classes, but when I try to calculate an EfficientFronter using `ef.max_sharpe()` I get the error  `Please check your objectives/constraints or use a different solver.`  This could potentially be related to #88 but I see that the OP was able to proceed by using the non convex solver from SciPy. While `max_sharpe()` fails, `min_volatility()` does not so I was wondering if the issue is related to the convexness of the problem, or the fact that I am trying to optimize both returns and volatility with assets that have fairly negative returns. For what it's worth I would expect the negative performing assets to be assigned 0 weights, but I could also theorize that those negative performing assets have the least volatility, making the problem unsolvable for max sharpe ratio? This is just conjecture and I'd like to hear your opinion on the matter.

**Comment by robertmartin8** [comment]
Hi @gtamba,

Thanks for the question! I think you're spot on with the explanation. If you have assets with very low volatility, that can also cause numerical problems (because it is in the denominator of the Sharpe ratio). All the more so if the numerator is negative. 

In a situation like this, I would try using a method like the [critical line algorithm](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimisers.html#the-critical-line-algorithm), which is a bit more robust.

Cheers,
Robert

**Comment by tmb-ltsdw** [comment]
Indeed the critical line algorithm did work for me without any optimization errors, thank you for the prompt response!

**Comment by gtamba** [comment]
Indeed the critical line algorithm worked for max_sharpe() without any optimization errors, thank you for the prompt response!
