### ISSUE TITLE
Allow the use of center of mass, half-life or alpha as alternatives to span

### ISSUE THREAD

**Issue by schneiderfelipe** [robertmartin8/PyPortfolioOpt#18]
Right now, `expected_returns.ema_historical_return` and `risk_models.exp_cov` support only using `span`, but it could be changed to allow direct usage of the other equivalent optional inputs of `pandas.DataFrame.ewm` (namely `com`, `span`, `halflife`, `alpha`). (`risk_models._pair_exp_cov` should be modified as well.)

This is simple to do. If there's interest, I could prepare a PR myself.

**Comment by robertmartin8** [comment]
Hi, thank you for the suggestion!

The reason I only wrapped `span` is because that typically in most finance-settings, we only talk about the "12-day moving average" or something similar – in this case the 12 represents the span (obviously if you have higher resolution data then the 12 refers to the increment). In the interests of keeping the API clean, I am inclined to leave this as is for now, unless people specifically need any of the others. But I will merge your current PR asap. 

Best,
Robert

**Comment by schneiderfelipe** [comment]
That's fine. I'm new to portfolio optimisation, I didn't know that :smile:.

All the best,
Felipe
