### ISSUE TITLE
How to choose optimal period for historical price data to construct covariance matrix?

### ISSUE THREAD

**Issue by mehmadi** [robertmartin8/PyPortfolioOpt#189]
**What are you trying to do?**
I am trying to find out what is the optimal time period to build cov matrix? Is there any recommended method to find this out?

I am asking this because for different starting points in backtest, using different time-periods results in different portfolio.

**Comment by robertmartin8** [comment]
Hi @mehmadi,

Thanks for the question! There is no correct answer for this, but here are a few thoughts:

- For calculating the sample covariance matrix, you need many more rows (dates) than there are columns (number of stocks), otherwise the covariance matrix may be ill-conditioned.
- There is a tradeoff between having a more "stable" estimated (larger window) and something that is more "relevant" (using a shorter window). My personal take is that you can use a method like [exponential covariance](https://pyportfolioopt.readthedocs.io/en/latest/RiskModels.html#pypfopt.risk_models.exp_cov) to compromise (though this trades one hyperparameter for another as you still need to input the span)
- The choice somewhat depends on your forecast horizon. If you are allocating assets for a long time horizon, it might be more justifiable to use a longer window (e.g all available data) for the covariance matrix. If you are going for a weekly/quarterly rebalance, I would suggest using 1y at most. 

Hope this helps!

**Comment by mehmadi** [comment]
Hi @robertmartin8,
Thanks so much for your recommendations and sharing your thoughts. I exactly experienced what you wrote in your third one: longer window sizes are better for longer horizons. However, it also depends on volatility of the market at the time of backtesting. 

Thank you again and thanks for such an awesome package!

**Comment by robertmartin8** [comment]
Indeed – ultimately one has to make a judgment call to choose the covariance calculation method / parameters to create something that will closely approximate the true future covariance. 

Don't hesitate to reach out if you have any more questions or issues!
