### ISSUE TITLE
How to use smaller frequencies (like hours)?

### ISSUE THREAD

**Issue by falgarcia** [robertmartin8/PyPortfolioOpt#190]
Hello!

I am trying to use PyPortfolioOpt in a cripto bot to enhance our portfolio optimization strategies. But all my ticker is collected in hour intervals (not days). The documentation leads to believe PyPortfolioOpt only works with daily data. 

For cripto, i used (frequency = 24*365) in the expected_returns and risk_models methods, but the results are kind of weird.

The mean_historical_return worked fine (i think), but the CovarianceShrinkage(dataset, frequency=24*365).ledoit_wolf() gives a very strange matrix (cant believe there is no covariance)

           BTC       LTC       ETH      TUSD       XRP
BTC   5.390544  0.000000  0.000000  0.000000  0.000000
LTC   0.000000  5.390544  0.000000  0.000000  0.000000
ETH   0.000000  0.000000  5.390544  0.000000  0.000000
TUSD  0.000000  0.000000  0.000000  5.390544  0.000000
XRP   0.000000  0.000000  0.000000  0.000000  5.390544

The price data seems ok, although the cripto prices are very different in scale.

What i am doing wrong ?

Thanks in advance !

**Comment by robertmartin8** [comment]
Hi @falgarcia,

Thanks for reaching out! There is definitely something wrong here. Here are some suggestions:

- Try a different method for calculating the covariance matrix (e.g sample covariance) and see if that works
- Use a frequency of 24. Then, the "annualised" covariance will actually be a "daily" covariance
- Try downsampling, e.g taking every 24th row. This will turn your data into daily data.

If you are able to share a sample of your data as a csv, I think it'll be quite easy to debug this.

Cheers,
Robert

**Comment by falgarcia** [comment]
Thanks for the quick response!!! I have tried your sugestions.

For covariance matrix alternative methods:
- CovarianceShrinkage.oracle_approximating(): **worked** (non zero matrix)
- CovarianceShrinkage.shrunk_covariance(): **worked** (non zero matrix)
- In fact, only CovarianceShrinkage.ledoit_wolf(shrinkage_target='constant_variance') resulted in the strange matrix. Using other shrinkage_target values worked (non zero matrix).

Using frequency of 24 didn't work so well. Gave me a lot of "pypfopt.exceptions.OptimizationError: Please check your objectives/constraints or use a different solver." regardless of the Covariance matrix used.

Downsampling to daily data **worked**, even with shrinkage_target='constant_variance'. But also resulted in a lot of "pypfopt.exceptions.OptimizationError" in data subsets (i use a rolling window to calculate portfolio allocations in backtesting). 

The CSV files are attached!
[data.zip](https://github.com/robertmartin8/PyPortfolioOpt/files/5190594/data.zip)

**Comment by robertmartin8** [comment]
Hi @falgarcia,

I'm so sorry for the late reply – have had a hectic couple of weeks. Really appreciate the testing with other `risk_models`, and I'm glad that at least some of the suggestions worked :)

However, if you are curious, I figured out what the problem is. Ledoit Wolf constant variance works by shrinking covariances to the mean of asset variances. So I computed the hourly variances using `df.pct_change().var()` and I got this:

```
BTC     0.000047
LTC     0.000331
ETH     0.000310
TUSD    0.626944
XRP     0.000347
dtype: float64
```

TUSD has a variance _way_ higher than everything else. This is what the time series looks like:



Because the TUSD has these strange spikes (data errors I think), it messes up the global mean volatility, which messes up the shrinkage. It is possible that TUSD is causing the other optimisation errors.

![Screenshot 2020-09-26 at 19 26 21](https://user-images.githubusercontent.com/11792905/94347706-56d18780-002e-11eb-8bf4-f1b4a779073c.png)

Hope this helps!

Robert
