### ISSUE TITLE
Adding other constraints with dict mapping?

### ISSUE THREAD

**Issue by dpsugasa** [robertmartin8/PyPortfolioOpt#208]
First off, I really like this library. You have considered many great things when creating it.

I would like to optimize a portfolio with sector constraints but also ratings constraints. How best to do this? My initial inclination was to create a dict with upper/lower, etc. like for the sector, but I am not sure if that is best.

Any thoughts would be appreciated.

**Comment by robertmartin8** [comment]
Hi @dpsugasa,

Could you please explain a bit more what you mean by "ratings constraints"? Like you want 0-20% AAA rated securities, 0-20% B rated, 0-20% C rated etc? 

If so, you should treat them exactly like sector constraints – a full example of that is [here](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/2-Mean-Variance-Optimisation.ipynb).

Hope this helps!

Robert

**Comment by dpsugasa** [comment]
Thanks Robert, yes that is correct. I want to limit exposure to certain ratings buckets as you suggest. So to do this, I would call `ef.add_sector_constraints` twice, first with a `sector_mapper` dict and then with a `ratings_mapper` dict? Correct?

**Comment by robertmartin8** [comment]
@dpsugasa That's correct! Be warned though - as you add more constraints, it becomes more likely that the optimiser will not be able to find an optimal portfolio that matches all the constraints, because there may not exist such a portfolio. So make sure your constraints are realistic. 

Hope it works out! Let me know if you have any issues.

Best,
Robert
