### ISSUE TITLE
How to minimize Tracking Error?

### ISSUE THREAD

**Issue by sven-borden** [robertmartin8/PyPortfolioOpt#216]
I am trying to create a convex objective to minimize the tracking error of a portfolio relative to a benchmark. 

The portfolio consists of a set of tickers `['MSFT', 'AMZN', 'KO', 'MA','COST', 'LUV', 'XOM', 'PFE', 'JPM', 'UNH', 'ACN', 'DIS', 'GILD', 'F']` and the benchmark is the SP500 (`'SPY'`). 

As the formula to compute the tracking error is the following: SQRT( Var(portfolio_returns - benchmark_returns)) I thought of writing the following function.

```python
def TE(w, portfolio_returns, benchmark_returns):
    """ 
    w -> (14,)
    portfolio_returns -> (154, 14)
    benchmark_returns -> (154,)
    """
    xi= (w @ portfolio_returns.T - benchmark_returns)
    mean = np.mean(xi)
    return cp.sqrt(cp.sum_squares(xi- mean) / xi.shape[0])

...

ef.convex_objective(TE, portfolio_returns=p_rets, benchmark_returns=b_rets)

...
```

But this gives me the following errors: `OptimizationError, Please check your objectives/constraints or use a different solver`.

Further Notes:

- I instanciated the efficientFrontier as follow : `ef = EfficientFrontier(mu, S)`
    - with `mu = expected_returns.mu = expected_returns.capm_return(...)`
    - with `S = risk_models.risk_matrix(method='ledoit_wolf', ...) `
- I didn't add any constraint yet

Is my process correct? I think I am close to the solution but I could not figure out how to make this works. Any advice would be helpful. 

Best

**Comment by robertmartin8** [comment]
Hi @sven-borden,

You're definitely along the right lines, but there are a couple of problems with your objective function (e.g what is `diff`?) For starters, can you try running it with a simplified version of your objective function?

```python
def TE(w, portfolio_returns, benchmark_returns):
    xi= (w @ portfolio_returns.T - benchmark_returns)
    mean = cp.sum(xi)/len(benchmark_returns)
    return cp.sum_squares(xi- mean)
```

Notice that although this function does not compute the tracking error, minimizing it is the same as minimizing the tracking error (minimising the sqrt of a value is the same as minimising the value because sqrt is monotonic). 

Let me know how that goes!

Best,
Robert

**Comment by sven-borden** [comment]
Thank you @robertmartin8, I tried with your snippet of code and it works great!

I really appreciate your quick and precise answer.
