### ISSUE TITLE
Integrate PyPortfolioOpt with an existing portfolio

### ISSUE THREAD

**Issue by ccx01-start** [robertmartin8/PyPortfolioOpt#240]
I have an existing portfolio that was manually allocated. I would like to use PyPortfolioOpt to optimize the weights going forward. What is the best way to achieve that? Can i reference the initial weights/current allocation?

**Comment by robertmartin8** [comment]
Hi @ccx01-start,

This depends on what exactly you are looking for. In other words, what don't you like about completely re-allocating your portfolio? Here are a few possibilities, and my suggestions in each case:

- Transaction costs: you want to make your allocation more efficient than it currently is, but not reallocate completely because it would incur large transaction costs as you rebalance. We can add a transaction cost term in the objective function, penalising large changes in weights. There is an example in [this notebook](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/3-Advanced-Mean-Variance-Optimisation.ipynb), under the heading "Min volatility with a transaction cost objective". 
- Efficient frontier optimisation might make some of your current weights negligible: to counter this, you can add a [L2 regularisation term](https://pyportfolioopt.readthedocs.io/en/latest/EfficientFrontier.html#more-on-l2-regularisation), which encourages the optimiser to allocate weight to all your assets.
- Your current allocation embeds your expectations of return, and you don't want this information to be lost in optimisation: in this case, it might be worth looking into [Black-Litterman allocation](https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html), which allows you to input your views of expected returns.

Hope this helps!
Robert

**Comment by ccx01-start** [comment]
Thanks @robertmartin8 for the detailed answer. I will take a look at the notebook but your suggestions do cover some of my concerns with the re-balancing. Is there a way to still use HRP while still setting the objective functions? I couldn't see how this would be possible with the API.

**Comment by robertmartin8** [comment]
@ccx01-start 

I'm afraid not, HRP works using a completely different paradigm, that is logically suited to minimising variance. Incorporating different objectives/constraints to HRP is still an active area of research

**Comment by robertmartin8** [comment]
Closing, but don't hesitate to reach out if you have other questions!
