### ISSUE TITLE
Solver defaults are not all compatible with the tolerances used in the unit tests.

### ISSUE THREAD

**Issue by SeaPea1** [robertmartin8/PyPortfolioOpt#246]
Therefore it can be necessary to explictly configure the solver to achieve the required tolerances, or configure np.testing.assert_almost_equal etc. tolerances to compensate.

**Comment by robertmartin8** [comment]
@SeaPea1 Hmm this is a valid issue but not something I want to spend much effort on. I can't find a simple reference for the tolerances of different cvxpy solvers (let me know if you come across one), but even if I did, the purpose of these tests is more to make sure I haven't broken something.

I am thus inclined to set the tolerances quite generously, since if I break something, the differences will be big anyway.

So maybe I'll just set everything at a relative tolerance of 1e-3 or 1e-4? Happy to hear your thoughts on this.

Appreciate all the bug reports, keep 'em coming! 😄

**Comment by SeaPea1** [comment]
Yes, is a bit complicated and appreciate it may not be something worth spending a long time on.

See https://www.cvxpy.org/tutorial/advanced/index.html - everything below "Here is the complete list of solver options.".  Unfortunately similar or identical settings are not consistently named across solvers, e.g. "eps_abs" & "eps_rel" vs. "eps".

With my linked pull request I've gone for a minimal, non-breaking change, so it is possible to specify the tolerances for the solver so users are not forced to specify the tolerances in each resulting np.testing.assert_almost_equal etc.  It  is probably easier for the users if they can specify the results they want.

I think ideally PyPortfolioOpt would configure each solver with param values such that the results could be compared with np.testing.assert_almost_equal etc. without a tolerance on those assert functions being overridden, so therefore it is no effort for the users of PyPortfolioOpt, i.e. "it just works".  However, that might be quite tricky in practice because the different solvers may not all be able to achieve the required tolerances in all cases (so may fail), or require a very large number of iterations causing an unacceptable performance hit.  I practice it might make life easier to standardise on 1 solver which PyPortfolioOpt would explicitly default to and test everything with a default set of overrides, but still allow users to specify their own if they really want/need  to.

**Comment by robertmartin8** [comment]
Fixed in v1.3.0
