### ISSUE TITLE
Feature request: Provide weightage to certain time periods for annual returns

### ISSUE THREAD

**Issue by linda390** [robertmartin8/PyPortfolioOpt#248]
Hi. Is it possible to provide more weightage to specific time periods when calculating the annual average return? Say that for ticker XYZ, I expect certain activity to typically occur during a presidential inauguration/election week and I want to provide more weightage (or less) for that specific week/month when calculating the average return,

I am currently calculating the average annual return for my tickers as an exponentially weighted mean via:

    averageAnnualReturn=annualReturns.ewm(span=500).mean().iloc[-1]

I would like to change this so that for certain tickers, I can ascribe more weightage to certain time periods from my dated closes.

Thank you.

**Comment by robertmartin8** [comment]
Hi @linda390,



It's not quite clear to me what you're after. 

PyPortfolioOpt primarily offers single-period optimisation. This means that that the optimal weights do not change over your time horizon (though of course, you can make your horizon short and rebalance frequently).

For example, if you are optimising a portfolio for the next 6 months, your goal should be to provide a vector of returns that best estimates the actual returns of the stocks in the next 6 months and the realised covariance matrix in the next 6 months. 

So are you saying that in order to estimate expected returns, rather than just taking the (exponential) mean of past returns, you would like to give a specific time in history more weight?

This could make sense if you thought that over your investment horizon, the assets would behave a lot like they did over some other period in history.

Best,
Robert

**Comment by linda390** [comment]
Hi.

"_So are you saying that in order to estimate expected returns, rather than just taking the (exponential) mean of past returns, you would like to give a specific time in history more weight?_"

That's correct.

I expect the stock returns to follow a certain pattern during weeks/months where are specific events, and therefore I would like to provide more weight to those selected time periods in history more weight.

**Comment by robertmartin8** [comment]
One way you can do this is to modify the `mean_historical_return` function to weight a particular set of dates higher. 

Here's an example computing the mean historical returns for a list of stocks, giving 5x the weight to returns in the week of Nov 2 - Nov 9:

```python
import pandas as pd
import yfinance as yf
from pypfopt import risk_models, expected_returns, plotting

# Get returns data
tickers = ["XLE", "XLF", "XLK", "XLV", "XLI", "XLP"]
df = yf.download(tickers, start="2019-01-01")["Adj Close"]
rets = expected_returns.returns_from_prices(df)

# Make weights column using the same datetime index as rets
weights = rets.assign(weights=lambda x: 1)["weights"]
# Set higher weights wherever you want
weights["2020-11-02":"2020-11-09"] = 5
# Compute annualised weighted average
weighted_mean_rets = rets.multiply(weights, axis=0).mean() * 252
```

Best,
Robert
