### ISSUE TITLE
Is it possible to use three sector constraints at the same time?

### ISSUE THREAD

**Issue by x829901** [robertmartin8/PyPortfolioOpt#249]
**What are you trying to do?**
Compute 20% target risk efficient portfolio with three sector constraints for region, size, and style. 

I have three sector mappers: 1) Region, 2) Size, 3) Style. Region assigns a region like U.S., Developed Markets, or Emerging Markets. Size assigns small-cap, mid-cap, large-cap to all my stocks. Style assigns value, growth, and blend to all my stocks. I don't want to combine them into one sector mapper, like "U.S. small-cap value", because I need to constrain them seperately. For example, applying a 50/50 value/growth constraint with a 60/30/10 to U.S., Developed Markets, Emerging Markets and 20/30/50 small-cap, mid-cap, large-cap constraint. This is an example of three constraints I want to apply, and be able to adjust them as needed separately. I have been combining them into a single mapper but I have no control over the individual sector. For example, if I combined constraint categories into say, "U.S. small-cap value", I have no control over how much of the U.S. or how much small-cap or how much value can be in the portfolio. I would only control how much could go to U.S. small-cap value. 

Here is what I have to far but I am getting a `OptimizationError: Please check your objectives/constraints or use a different solver.` 

```
gamma=0.00
ef = efficient_frontier.EfficientFrontier(mu, S, weight_bounds=(0,1))
ef.add_sector_constraints(region_mapper, region_lower, region_upper)
ef.add_sector_constraints(size_mapper, size_lower, size_upper)
ef.add_sector_constraints(style_mapper, style_lower, style_upper)
ef.add_objective(objective_functions.L2_reg, gamma=gamma)
ef.efficient_risk(0.2)
```

Any help is very much appreciated.

**Comment by robertmartin8** [comment]
Hi @x829901,

Thanks for reaching out!

What you are suggesting should be possible – I can't see anything wrong with your code. This is what I've tested, and it works fine:

```python
sector_mapper = {
    "MSFT": "Tech",
    "AMZN": "Consumer Discretionary",
    "KO": "Consumer Staples",
    "MA": "Financial Services",
    "COST": "Consumer Staples",
    "LUV": "Aerospace",
    "XOM": "Energy",
    "PFE": "Healthcare",
    "JPM": "Financial Services",
    "UNH": "Healthcare",
    "ACN": "Misc",
    "DIS": "Media",
    "GILD": "Healthcare",
    "F": "Auto",
    "TSLA": "Auto"
}

sector_lower = {
    "Consumer Staples": 0.1, # at least 10% to staples
    "Tech": 0.05 # at least 5% to tech
    # For all other sectors, it will be assumed there is no lower bound
}

sector_upper = {
    "Tech": 0.2,
    "Aerospace":0.1,
    "Energy": 0.1,
    "Auto":0.15
}

style_mapper = {
    "MSFT": "mega",
    "AMZN": "mega",
    "KO": "mid",
    "MA": "big",
    "COST": "big",
    "LUV": "big",
    "XOM": "mid",
    "PFE": "big",
    "JPM": "big",
    "UNH": "mid",
    "ACN": "mid",
    "DIS": "big",
    "GILD": "mid",
    "F": "mid",
    "TSLA": "big"
}

style_lower = {
    "mega": 0.1,
    "big": 0,
    "mid":0
}

style_upper = {
    "mega":0.8,
    "big": 1,
    "mid":0.5
}

mu = expected_returns.capm_return(prices)
S = risk_models.CovarianceShrinkage(prices).ledoit_wolf()

ef = EfficientFrontier(mu, S)  # weight_bounds automatically set to (0, 1)
ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
ef.add_sector_constraints(style_mapper, style_lower,style_upper)

# Another constraint (to show it's possible)
amzn_index = ef.tickers.index("AMZN")
ef.add_constraint(lambda w: w[amzn_index] == 0.10)

ef.efficient_risk(0.2)
weights = ef.clean_weights()
```

So I suspect the issue is that your optimisation problem is infeasible, i.e it is not possible to find a solution satisfying your constraints, let alone an optimal one. I suggest the following.

1.  Temporarily remove some constraints (e.g comment out style and size) and verify that the solver works. Since you are using `gamma=0`, you might want to remove that constraint completely.
2. Add back your constraints, but this time widen the lower/upper bounds to e.g 0.1/0.9. If this doesn't work, try widening it all the way to 0/1 – I'd be surprised if this didn't work, since this isn't actually adding a constraint. 
3. Move individual lower/upper bounds to your desired values, rerunning the optimisation each time. At some point, the solver may go from working to not-working, which will identify the infeasible constraint for you. 

Also, you should run the optimisation with `verbose=True` and paste the output here.

```python
ef = efficient_frontier.EfficientFrontier(mu, S, weight_bounds=(0,1), verbose=True)
```

CVXPY does have a feasibility check but I don't think PyPortfolioOpt's `BaseConvexOptimizer` exposes that. I've raised this in #250 and will try to incorporate it in the next patch so that things are easier to debug.

**Comment by x829901** [comment]
Excellent. Thanks for your help.
