### ISSUE TITLE
How to set up min and max constraints?

### ISSUE THREAD

**Issue by mreismendes** [robertmartin8/PyPortfolioOpt#254]
Hi,

I've got stuck trying to add min and max constraints to `EfficientFrontier`.

It's a semi-continuous problem! If the asset is chosen it must be above minimal, if not, must be 0.

Colab link: https://drive.google.com/file/d/1aFBCecCBBkLuFgeUAVUzd33K1KykK0Bq/view?usp=sharing
![image](https://user-images.githubusercontent.com/32521301/104628192-b2c02a80-5676-11eb-8424-a47f8d1f75ca.png)

`constraint_min` is a NumPy array that has the minimum allocation for each asset.
![image](https://user-images.githubusercontent.com/32521301/104628291-d1262600-5676-11eb-92da-cfba3ade7a05.png)

When I don't add constraints it works flawlessly:
![image](https://user-images.githubusercontent.com/32521301/104628410-f74bc600-5676-11eb-8bad-2b7a2f8884ef.png)

I'd appreciate any kind of help.

Thank you

**Comment by robertmartin8** [comment]
Hi @mreismendes,

Interesting problem. As I'm sure you've realised, the reason why the current code doesn't work is that your `constraint_min` has a sum greater than 1. 

I'll have a think about whether your constraint (zero weight OR weight > c) can be expressed in PyPortfolioOpt/cvxpy (paging @phschiele). 

My initial thought would be to introduce a new cvxpy boolean vector, which controls whether an asset is included in portfolio, along with the standard inequality constraint. But I'll need to think about how this could be expressed in PyPortfolioOpt.

Best,
Robert

**Comment by mreismendes** [comment]
Hi @robertmartin8 

That functionality would be awesome. In this specif case, I'm optimizing a portfolio of funds where each fund has its minimal investment, therefore, if the fund is selected it must be at least a minimum weight based on your available capital.

Thank you!

**Comment by robertmartin8** [comment]
@mreismendes Good news! Here's a solution:

```python
import cvxpy as cp

ef = EfficientFrontier(mu, S, solver="ECOS_BB")

k = cp.Variable(len(mu), boolean=True)
mins = np.ones(len(mu)) * 0.03   # define your vector, doesn't have to be constant
maxs = np.ones(len(mu)) # must have maxmium also

ef.add_constraint(lambda x: x >= k @ mins)
ef.add_constraint(lambda x: x <= k @ maxs)
ef.min_volatility()
```

I don't think this will work so nicely with max sharpe, but should be fine for most of the other objectives.

Let me know if that works for you!

Best,
Robert

**Comment by mreismendes** [comment]
Hi @robertmartin8 
Why does sharpe not work?
Thank you!

**Comment by robertmartin8** [comment]
@mreismendes 

To formulate max sharpe as a convex problem, you have to perform a funky variable substitution (see [here](https://people.stat.sc.edu/sshen/events/backtesting/reference/maximizing%20the%20sharpe%20ratio.pdf)).

This is not hard to do for a particular problem (if you were writing it in scratch from CVXPY) but is quite hard from PyPortfolioOpt's perspective, since we have to rebuild the constraints using the new variables (the [code](https://github.com/robertmartin8/PyPortfolioOpt/blob/8eb2a16c56579712a640b6e256727dd9dd8e6694/pypfopt/efficient_frontier.py#L204) is pretty weird, as you can see).

The result is that for simple constraints, `max_sharpe` works and respects the constraints, but for complicated ones, the substitution might mess it up. 

For your particular problem, the code I provided _might_ work with `max_sharpe` (note I've renamed `k` into `b` since PyPortfolioOpt uses another `k` on the backend), but I haven't tested it.

I have, however, checked that it works with `efficient_return`.

Hope this helps!
Robert
