### ISSUE TITLE
weight_bounds=(0.15, 0.35) not working

### ISSUE THREAD

**Issue by MarcelDelhez** [robertmartin8/PyPortfolioOpt#258]
Robert,
First of all, nice job you did there.  I tried to understand your code and congrats for what you wrote.
Still, when trying it, I encountered issues when trying to fix the weight bounds for having diversified portfolios but not too much.  Assuming the investor don't have millions to invest, it is necessary to limit the weight bounds so that he do not have to buy one share of each instrument.
So, I tried with 73 shares, calculated expected returns and built a covariance matrix.
Then I tried the EfficientFrontier with weight_bounds and received the error to use another solver or adjust the constraints.  Here, error is well managed same if not any of the solvers of cvxopt is giving a result (I tried them all).
When using the CAL optimizer, it came out with a bound error into the initialization of cla.py (line 126) because, after the loop, it tries to access b[73] which do not exist as its shape is 73.  This is because it did not entered the loop and never did the i-=1 I assume.

When using weight_bounds(0, 1) everything works fine but,  as I wrote, with 73 shares as input, result is too diversified.  There are weights on every shares. 

But, somewhere, you answered to this post into the #243 when you say that portfolio optimisation is not assets selection.  I can play with the gamma on a restricted set of shares (to reduce very small weights) but still a bit disappointing that weight_bounds is not working.  I assume it is not working because every allocations calculated are out of the bounds specified (it is what I observed when looking at the generated weights without specifying bounds).  So, my conclusion is that it is better to first select a small number of assets and then calculate weights for those assets.

**Operating system and python version:**
Windows 10, python 3.7

**Comment by robertmartin8** [comment]
Hi @MarcelDelhez,

The reason that you are receiving a bug is that your lower weight bound is too high. You have put 15% as a minimum, but you said you have 73 assets. 73 * 15% is well above 100%. 

In otherwords, there does not exist a portfolio that satisfies your constraints (weights sum to one and minimum is 15%), let alone an optimal one. You should decrease the lower weight bound, eg:

```python
ef = EfficientFrontier(mu, S, weight_bounds=(0.005, 0.1))
ef.min_volatility()
```

`gamma` won't help you here, because it is meant to _increase_ diversity (see #257 for discussion about decreasing diversity). #254 might be more appropriate: it forces the optimiser to give either zero weight or a minimum weight.

Best,
Robert

**Comment by MarcelDelhez** [comment]
Yes of course …

I was for sure drunk that day.  Not able to calculate that … shame on me

 

 

 <https://be.linkedin.com/in/marceldelhez?trk=profile-badge-name> Marcel Delhez

Domain Architect - Project Manager - Agile Scrum Master – Chapter Lead

Phone : 0485/90.14.09

e-mail :  <mailto:md@marcel-delhez.eu> md@marcel-delhez.eu

 

 <https://be.linkedin.com/in/marceldelhez?trk=profile-badge-cta> View profile
