### ISSUE TITLE
Can't pass None as expected_returns to EfficientCVaR & EfficientSemivariance

### ISSUE THREAD

**Issue by Biszu** [robertmartin8/PyPortfolioOpt#324]
Passing None as expected_returns to EfficientCVaR or EfficientSemivariance fails, due to
`TypeError: object of type 'NoneType' has no len()`

The error is caused by the following line:
`cov_matrix=np.zeros((len(expected_returns),) * 2),  # dummy`

PyPortfolioOpt v1.4.1, Python v3.8

**Comment by robertmartin8** [comment]
Hi @Biszu,

Good spot, this is a really silly bug from me. I think I just need to change `len(expected_returns)` to `returns.shape[1]` since `returns` is required.

Will push a fix when I can. In the meantime, passing a dummy vector of the correct length should allow the code to be used.

Cheers,
Robert
