### ISSUE TITLE
Is it possible to define max weight constraint per sector map constraint?

### ISSUE THREAD

**Issue by blenderben2** [robertmartin8/PyPortfolioOpt#341]
**What are you trying to do?**
For example, if I have a sector constraint like so:
```
sector_mapper = {'AAA': 'stocks', 
		 'BBB': 'stocks',
                 ....,
		 'CCC': 'bonds',
		 'DDD': 'bonds', 
                 ....,}
sector_lower = {'stocks': 0.7, 'bonds': 0.3}
sector_upper = {'stocks': 0.7, 'bonds': 0.3}
ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
```
as you can see my lower and upper bounds are the same implying that I want my portfolio to have **fixed** 70% stocks and 30% bonds. However, within each asset class (stock/bond) I want it to have a maximum weight per asset.

For example for each asset in stocks can only have a maximum weight of 30%, in this case if the algo goes all in, it will have 4 assets under stock (30%, 30%, 30%, 10%) for stock. Similarly, if each asset in bonds can have a maximum of 50%, then it will have 2 assets (50% each) for bond. Thus, the total portfolio will have 4+2 assets = 6.

**What have you tried?**
In addition to the above code, I have added a constraint like:

`ef.add_constraint(lambda x : x <= 0.2)`

However, this affects all the assets regardless of which asset class it is under. Also, this 20% is in regards to the total (weights) portfolio and not the sub-weights.

PS, by sub-weights I mean the 70% of stocks above to be treated as 100%. So when I want to implement max weight per stock asset of 30%, its actually 21% of the total portfolio

**Comment by phschiele** [comment]
@blenderben2 Great question. Let's look at the equality and inequality constraints of your problem separately. 
**Equality:** 
You want a fixed ratio of stock and bonds (I assume no shorts are allowed). 
Let `x1, x2, x3, x4` be the stocks and `x5, x6` be the bonds, such that our weight vector looks like this: `x = [x1,x2,x3,x4,x5,x6]`.
To get the stocks/bond ration, you need to define the constraint
`[1,1,1,1,0,0] @ x == 0.7`
This simply means that when only "counting" the stocks, the weights need to add up to 0.7. Of course, we do not need the corresponding constraint for bonds, because if we invest 70% into stocks and the weights need to add up to 100%, 30% must be in bonds (given that there are no other asset classes). By defining the lower and upper bounds as equal, you basically already have the equality constraints in place. 

**Inequality:**
You say that each stock should be at most 30% of the total stock weights. I assume that you mean when e.g. stocks are currently at 50% weight in total, each stock should at most have 15%, and so on. 

Starting with x1, this basically means:
`x1 <= 0.3 * (x1 + x2 + x3 + x4)`
Now lets rearrange terms:
`0.7*x1 - 0.3*x2 - 0.3*x3 - 0.3*x4 <= 0`, which in matrix form means:
`[0.7,-0.3,-0.3,-0.3,0,0] @ x <= 0`. That would need to be added for `x1, ... x4`, of course.

Similar constraints can be added for bonds, but notice that when you have two bond assets and each should have a maximum weight of 50%, that means both assets can _only_ ever have 50%. If this is intended, it would be in fact also be an equality constraint.

**Comment by blenderben2** [comment]
hi @phschiele sorry for the late reply, and thanks for the detailed response. From your answer, it seems like this cannot be done with the current `add_constraint` method and it seems like it has to be done on an individual basis (per asset), which is not ideal if we have over 100 assets :/

**Comment by robertmartin8** [comment]
@blenderben2 when you say 

>within each asset class (stock/bond) I want it to have a maximum weight per asset.

Do you mean that OF the 70% allocated to stocks, the maximum weight of a given stock is 30%?

E.g for a $1000 portfolio, you want $700 allocated to stocks, of which no single stock can be more than $210? (30% of 700).

In this case, surely you just need to put a 70% * 30% weight constraint on each stock?

```python
max_stock_weight = 0.3 #0.3 of the 0.7
total_stock_weight = 0.7

max_weight = []
for i in asset_list:
    if sector_mapper[i] =="stocks":
          max_weight.append(max_stock_weight * total_stock_weight))
     elif sector_mapper[i] == "bonds":
          max_weight.append(max_bond_weight * total_bond_weight)
```

The result of this will be a list of maximum weights, taking into account whether the asset is a stock or a bond.

Then you should just be able to

```python
ef.add_constraint(lambda x: x < np.array(max_weight))
```

Combined with @phschiele's solution for the equality constraint, this should work?

**Comment by blenderben2** [comment]
> E.g for a $1000 portfolio, you want $700 allocated to stocks, of which no single stock can be more than $210? (30% of 700).

yes this is what I mean.

Thanks for the suggestions I will try them out and get back.
