### ISSUE TITLE
Max-Sharp-Ratio optimizer with a risk-free asset

### ISSUE THREAD

**Issue by akhorshidi** [robertmartin8/PyPortfolioOpt#346]
**What are you trying to do?**
Suppose we want to make an investment in some risky assets and one risk-free asset. The risk-free rate or annual return on the risk-free asset is 10%. 
We have a 3-month length data frame of daily returns, where the last column contains the constant daily return value for the risk-free asset. 

**What have you tried?**
Please see the sample notebook I've provided at the following link: 
https://colab.research.google.com/drive/1AA3bUsbhGZlnt-10rksT8grUJFzNKGOu?usp=sharing

**What data are you using?**
My questions regarding `efficient_frontier.max_sharpe()` optimzer are:

1- How should the value of the `risk_free_rate` argument be scaled such that it becomes consistent with the expected return of the risk-free asset? 

Let's try three different values for the input argument `risk_free_rate` and compare the results. 
First, suppose the value of `risk_free_rate` equals the annualized risk-free rate, `rf = 0.1`. 

```
ef = EfficientFrontier(mu, cmat) 
ef.max_sharpe(risk_free_rate=rf)
weights = ef.clean_weights()
```

> OrderedDict([('BTCUSDT_close', 0.04747),
>              ('ETHUSDT_close', 0.59387),
>              ('XRPUSDT_close', 0.29213),
>              ('DOGEUSDT_close', 0.06654),
>              ('RF_asset', 0.0)])

**_It assigns no weight to the risk-free asset._** 

Let's see what happens when we assign the value of the daily risk-free return, 
i.e. `rf/252`, to the input argument. 

```
ef = EfficientFrontier(mu, cmat) 
ef.max_sharpe(risk_free_rate=rf/252)
weights = ef.clean_weights()
```

> OrderedDict([('BTCUSDT_close', 0.0),
>              ('ETHUSDT_close', 0.0),
>              ('XRPUSDT_close', 0.0),
>              ('DOGEUSDT_close', 0.0),
>              ('RF_asset', 1.0)])

**_It offers to invest all our money in the risk-free asset!_**

What would happen if we choose the value of the input argument equals 3-month risk-free return, `rf/252 * 90`? Note that the length of our dataframe is 90 days.

```
# 3-month risk-free rate
rf3M = rf/252 * TRADING_DAYS
ef = EfficientFrontier(mu, cmat) 
ef.max_sharpe(risk_free_rate=rf3M)
weights = ef.clean_weights()
```

> OrderedDict([('BTCUSDT_close', 0.07115),
>              ('ETHUSDT_close', 0.36634),
>              ('XRPUSDT_close', 0.18497),
>              ('DOGEUSDT_close', 0.03971),
>              ('RF_asset', 0.33783)])

**_Now it says that we should maintain about a third of the portfolio in the risk-free asset._** 

2- Another question raised here is, 
How we can interpret the results of these three cases? 

3- The last question, when I've tried to construct a portfolio based on the Max-Sharp-Ratio strategy with 10 or 20 risky assets and one risk-free asset, the sum of the weights returned by the optimizer is less than 0.9! In other words, the sum of all the weights in each portfolio is between 0.85 and 0.9 and does not add up to unity!

BTCUSDT_close | ETHUSDT_close | XRPUSDT_close | DOGEUSDT_close | BNBUSDT_close | ADAUSDT_close | USDCUSDT_close | DOTUSDT_close | UNIUSDT_close | BCHUSDT_close | LTCUSDT_close | LINKUSDT_close | SOLUSDT_close | RF_asset
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0 | 0.01743 | 0.0941 | 0.10254 | 0.15167 | 0 | 0 | 0.0458 | 0 | 0 | 0 | 0.43679 | 0

**Comment by robertmartin8** [comment]
Hi @akhor,

The `risk_free_rate` parameter should correspond to the same time period as the expected returns you supply to the optimiser.

For example, it is common to convert daily prices to annualised returns using `mean_historical_return(prices, frequency=252)`. In this case, the `risk_free_rate` parameter should be an annualised value. 

If you are supplying the expected 3-month return, then `risk_free_rate` should be the 3-month value. 

### Interpreting results

With the above in mind, I'll now attempt to interpret some of the results you've seen. In order to avoid getting confused, I will refer to your risk-free asset as "asset X".

> suppose the value of risk_free_rate equals the annualized risk-free rate, rf = 0.1.

The optimiser now sees a `risk_free_rate` of 10%. Your asset returns are: 

`[0.80140177 1.14685261 1.20867782 5.30573032 0.03571429]`.

Note that asset X is returning much less than the risk-free rate, so from the perspective of the optimiser, asset X contributes negatively. This explains the zero weight.

> Let's see what happens when we assign the value of the daily risk-free return, i.e. rf/252, to the input argument.

In this case, the optimiser sees a `risk_free_rate` of 0.04%, while the asset returns are unchanged. Now notice that asset X returns much more than the `risk_free_rate`. Because asset X has zero volatility, the Sharpe ratio is indeed maximised by putting 100% into the risk-free asset (volatility = 0 means that mu/vol goes to infinity). 

> What would happen if we choose the value of the input argument equals 3-month risk-free return, rf/252 * 90?

This is the "correct" setup. Asset X now has a return equal to the risk-free rate. There's not much to explain here – the risk-free asset receives a high weighting because it has zero volatility. If you reduce the return of asset X (i.e reduce the risk free rate), you should see the allocation to asset X go down. 

### Conclusions

I think the main takeaway here is that you should be very careful using `max_sharpe` in the presence of a risk-free asset – because it has zero vol, it can easily results in numerical issues. 

Could you please raise a separate issue for your 3rd question and include a code sample (ideally with your vector of expected returns and cov matrix too)

Hope this helps!
Robert

**Comment by akhorshidirad** [comment]
Hi Robert

Thank you very much for interpreting and explaining it. Now everything sounds good to me. 
Regarding the third case, I'll open a new issue with a sample code to reproduce the results. 

Merci

Mehran

**Comment by akhorshidi** [comment]
Hi Robert

Thank you very much for interpreting and explaining it. Now everything sounds good to me.
Regarding the third case, I'll open a new issue with a sample code to reproduce the results.

Merci
Mehran
