### ISSUE TITLE
Possibility to adjust Sharpe Ratio by ESG parameter?

### ISSUE THREAD

**Issue by lealik** [robertmartin8/PyPortfolioOpt#444]
Hi, 

I am trying to do a portfolio optimization based on an ESG adjusted Sharpe Ratio. Hereby, I was wondering whether it is possible to adjust the Sharpe Ratio as the following: 

SR=  ((μ- rf)/σ)   +  (ESG/σ) 

Before finding this portfolio optimiser, I have tried to do it based on a Monte Carlo simulation using the following optimisation function: 

optimal_portfolio = portfolios.iloc[(((portfolios['Returns']-rf)/portfolios['Volatility'])+(portfolio ['ESG Score']/portfolios['Volatility'])).idxmax()]

which however did not lead to sufficient results, due to the size of our investment universe (around 500 stocks). 

Many thanks for your help in advance!

Best, 
Lea

**Comment by robertmartin8** [comment]
Conceptually, it seems a bit strange to do it that way unless your ESG score has the same units as return.

For example, let's say your ESG scores are 1,2,3,4,5. Since returns are of order 10%, the result would be an optimiser that focuses primarily on ESG score divided by volatility. 

In my view, it would make more sense to use ESG as a constraint: maximise the Sharpe ratio of the portfolio subject to an ESG constraint.

Alternatively, a nice trick might be to embed ESG into the expected returns vector. e.g you may decide "1 ESG point" is worth an extra 1% return, then just add this to the expected returns. This may seem arbitrary, but it is no different to the original proposed optimisation. 

Interesting question!

**Comment by lealik** [comment]
Yes, we adjusted the ESG scores such that they have the same unit as returns. 

But thanks, the idea of embedding ESG into the expected return vector is great!
