### ISSUE TITLE
Why not consider excess returns?

### ISSUE THREAD

**Issue by mdmcconnell** [robertmartin8/PyPortfolioOpt#519]
This is more of a question of background or curiosity than any sort of issue with PyPortfolioOpt implementation.  I am working on moving some portfolio optimisation exercises I do from Excel/VB to Python and learning lot in the process just by reading the project documentation, which is really well done.

The PyPortfolioOpt library and all of the optimisation examples proceed using absolute returns.  In building an investment portfolio, I think I am more interested in _excess_ returns.  By ignoring the fact that in some periods I can earn greater or lesser returns risk free, won't I effectively overweight my Sharpe ratio optimisation to periods with high risk free rates (and assuming commensurately higher asset returns)?  Or does the underlying math obviate that concern?  Was there a rationale behind the decision to work with absolute returns?

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
In short: It depends on your data and you can do it yourself.

Long answer: Yes, you’re right. In many formulas and optimizations, we should use excess returns. However, excess returns depend on a chosen benchmark for the same period. This means that it depends on your data and is out of our control. Fortunately, you can calculate excess returns by subtracting the return of a benchmark (or risk-free return) from the absolute return and then feed it into this library. This makes it easier for both you and us so that we can focus on the optimization process. I hope this helps.
