### ISSUE TITLE
CVar Bugs?

### ISSUE THREAD

**Issue by asjem** [robertmartin8/PyPortfolioOpt#52]
Just a q. 

Really like the lib, thank you.

I notice this comment in the examples "# CVaR optimisation - very buggy"

What are the known issues? I'm keen to use so maybe I can try and fix some of them on the way.

Cheers

**Comment by robertmartin8** [comment]
Hi,

The difference between CVaR and most of the other objective functions in PyPortfolioOpt is that CVaR is a stochastic objective: for a given portfolio, we calculate the CVaR by generating a sample of returns then computing the mean of all losses below e.g the 5th percentile. The problem is that this procedure can return very different values on each call – I have observed this to be true even when using very large samples. Thus even computing the objective function is nontrivial.

But computing the objective function is normally the easy part – the true difficulty is optimising over the objective function. To that end, I have delegated this to [NoisyOpt](https://noisyopt.readthedocs.io/en/latest/). 

In my experience however, this is extremely unstable. See issues #5 and #15  for more.

Best,
Robert
