### ISSUE TITLE
"Unexpectedly insufficient funds." when using greedy_portfolio

### ISSUE THREAD

**Issue by NiklasMelton** [robertmartin8/PyPortfolioOpt#528]
Since this is a raised error its obviously a known issue but I would like to suggest a solution

This error is raised when weights are passed that sum to >1. 

IMO, the ideal behavior would be to always check that weights sum <=1 and raise a warning when this is not the case. Then, simply normalize the weights. The following snippet would do the trick if added to the beginning of the function:

```
weight_sum = sum(w[1] for w in self.weights)
if not np.isclose(weight_sum, 1):
    if weight_sum < 1: 
        warnings.warn("Weights sum < 1. This may result in non-optimal behavior")
    if weight_sum > 1:
        warnings.warn("Weights sum > 1. Please check your optimizer. Weights will be normalized.")
        self.weights = [(s, w/weight_sum) for s, w in self.weights]
```

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
@NiklasMelton could you please provide more information and/or a minimum working example to reproduce that issue? Because the weights should always be 1, not less and not more than 1.

There is a case where the weight_sum is close to 1 as in your code. It’s just because of Python’s numeric problem and we accept that issue. IMO, in np.isclose, we could use rtol = 0.01% (default is 1e-05) OR atol = 0.0001 (default is 1e-08).

In other cases where the weight_sum is not close to 1, there may be a problem with the optimizer. Maybe your result is not optimal. If you can make sure that your result is optimal and the total is still greater than 1, then yes, in this case you could normalize the weights.
