### ISSUE TITLE
What is the right input to EfficientSemivariance?

### ISSUE THREAD

**Issue by codemaniac** [robertmartin8/PyPortfolioOpt#597]
I am confused what is the right input to pass to `EfficientSemivariance`.

The documentation says ` Instead of passing in a covariance matrix, you should past in a dataframe of historical/simulated returns (this can be constructed from your price dataframe using the helper method expected_returns.returns_from_prices())`

But, the example code uses `mu = expected_returns.mean_historical_returns(df)` as the first argument to `EfficientSemivariance`.

By my understanding, `expected_returns.returns_from_prices()` returns **daily percentage change** using `prices.pct_change()` but `expected_returns.mean_historical_returns(df)` returns **annualized returns** by default.

Please help! What is the correct input?

**Comment by robertmartin8** [comment]
EfficientSemivariance tries to construct a mean-semivariance frontier, instead of a mean-variance frontier.

To estimate the mean, you can use methods like `expected_returns.mean_historical_returns`. 

To estimate the semivariance, unlike `EfficientFrontier`, you can't just pass a covariance matrix. You need to pass the percentage returns (output of `returns_from_prices`), so that `EfficientSemivariance` can directly optimise semivariance.
