### ISSUE TITLE
feature request: prediction with ARIMA-LSTM

### ISSUE THREAD

**Issue by trbck** [robertmartin8/PyPortfolioOpt#8]
This looks great! Thanks for sharing!

Might also want to implement correlation coefficient prediction with ARIMA-LSTM, as published here https://arxiv.org/abs/1808.01560

**Comment by robertmartin8** [comment]
Thank you very much for the suggestion – I was quite skeptical initially but the results look reasonably impressive. 

However, I feel that for the time being this is a little bit too specialised to be added into `pypfopt` (particularly because of the dependencies it would entail). `pypfopt` is designed to be able to work with complex models like this, but perhaps they shouldn't be part of the API itself. Happy to hear people's thoughts on the matter.

Robert
