### ISSUE TITLE
Cannot pass None as expected_returns anymore

### ISSUE THREAD

**Issue by fl4p** [robertmartin8/PyPortfolioOpt#83]
In the docs of `EfficientFrontier.__init__` it says `expected_returns` can be None if optimising for min volatility. However, this does not work anymore, since  `_validate_expected_returns` raises and exception.

**Comment by robertmartin8** [comment]
@fl4p 

Thanks for raising this, that's a big issue and I'll fix it ASAP. I can't believe I don''t have a test that covers this!

Robert

**Comment by robertmartin8** [comment]
@fl4p 

I've just fixed this; if you `pip install --upgrade pyportfolioopt`  it should all work now. Let me know if you have any further issues!

One thing that I would say is that if you are able to provide expected returns, I would suggest you do so – otherwise `portfolio_performance` can't give you returns or a Sharpe ratio :)

Best,
Robert

**Comment by fl4p** [comment]
@robertmartin8  Works as expected now, thanks!

Ok, didn't know about `portfolio_performance`, I compute SR etc externally. Will take a look at it
