### ISSUE TITLE
Compounding in `mean_historical_returns`

### ISSUE THREAD

**Issue by gauravsofat** [robertmartin8/PyPortfolioOpt#85]
Hi Robert, I'm new to portfolio management and have been using PyPortfolioOpt for the past few days. I have been finding the library extremely useful and interesting.

I was hoping you could clarify the way `mean_historical_returns` annualises returns, according to [this](https://github.com/robertmartin8/PyPortfolioOpt/blob/7a06bee5efc0c061b41485c0c4b1e74e38eff9a5/pypfopt/expected_returns.py#L70) line the mean daily returns are multiplied by 252 (the number of trading days in a year). Shouldn't the mean value be compounded over this period? 

Thus if the mean daily return for an equity is `x`, the annualised mean daily return would be `[ (1+x) ^ 252 ] - 1` instead of `x * 252`. Would be more than happy to submit a PR if indeed this should be changed.

**Comment by robertmartin8** [comment]
Hi @gauravsofat,

Thanks for reaching out! This is a somewhat arbitrary decision, and within finance there are many different conventions. For example, if you take professional sources of returns (like Barra), they generally do not use the compounding calculation.

But you are correct that this should be better documented.  I think the best way forward would be to modify the current `mean_historical_return` function to have an optional boolean parameter `compounded=False`. If `compounded=True`, then we can instead do the compounding calculation. Let me know if you're keen on implementing that, otherwise I can do so.

Best,
Robert

**Comment by gauravsofat** [comment]
Sure, I'd be glad to make a contribution to that effect. 
Shall open a PR which implements the `compounded` boolean parameter asap.
