### ISSUE TITLE
cant make custom convex objective function work

### ISSUE THREAD

**Issue by dao72** [robertmartin8/PyPortfolioOpt#90]
Need to minimize Variance*k -  E(return)

what am i doing wrong?

```python
def kelly_objective(w,e_returns,cov_matrix, k=3):
    variance = np.dot(w.T, np.dot(cov_matrix, w))
    objective = variance*0.5*k - np.dot(w, e_returns)  
    return objective

mu = expected_returns.mean_historical_return(df, frequency = 1)
S = risk_models.sample_cov(df, frequency = 1 ) 
ef = EfficientFrontier(mu, S, weight_bounds = ( bound_lower, bound_upper ) )
    
wts = ef.convex_objective(kelly_objective,e_returns = mu, cov_matrix=S, k = 3) 
```

I get an error.  

```
5 frames
/usr/local/lib/python3.6/dist-packages/cvxpy/interface/numpy_interface/ndarray_interface.py in const_to_matrix(self, value, convert_scalars)
     48             return result
     49         else:
---> 50             return result.astype(numpy.float64)
     51 
     52     # Return an identity matrix.

ValueError: setting an array element with a sequence.
```

What do i need to do ? used to work just fine when you had custom objective function

**Comment by robertmartin8** [comment]
Hi @dao72,

Thanks for reaching out! There are a few options to make this work. Since your objective is convex, you are correct that the best method is `ef.convex_objective()`. However, the objective function must be built with `cvxpy` functions:

```python
def kelly_objective(w, e_returns, cov_matrix, k=3):
    variance = cp.quad_form(w, cov_matrix)

    objective = variance * 0.5 * k - w @ e_returns
    return objective

weights = ef.convex_objective(
    kelly_objective, e_returns=ef.expected_returns, cov_matrix=ef.cov_matrix
)
```

However, in this case, I'd encourage you to use the built in `ef.max_quadratic_utility()` (documented [here](https://pyportfolioopt.readthedocs.io/en/latest/EfficientFrontier.html#pypfopt.efficient_frontier.EfficientFrontier.max_quadratic_utility)), since it is very similar to your objective, just with slightly different scaling.

Alternatively, if you weren't sure that your objective were convex, you could use `ef.nonconvex_objective()`:

```python
def kelly_objective(w, e_returns, cov_matrix, k=3):
    variance = np.dot(w.T, np.dot(cov_matrix, w))
    objective = variance * 0.5 * k - np.dot(w, e_returns)
    return objective

lower_bounds, upper_bounds = 0.01, 0.3
weights = ef.nonconvex_objective(
    kelly_objective,
    objective_args=(ef.expected_returns, ef.cov_matrix, 3),
    constraints=[
        {"type": "eq", "fun": lambda w: np.sum(w) - 1},  # weights sum to one
        {"type": "ineq", "fun": lambda w: w - lower_bounds},  # w >= lower bound
        {"type": "ineq", "fun": lambda w: upper_bounds - w},  # w <= upper bound
    ],
)
```

Though as I said, in your case it's best to use the `convex_objective`.

Hope this helps! Please let me know if you're having any other issues :)

Best,
Robert

**Comment by dao72** [comment]
Hi Robert

Thanks a lot for your reply.
I actually figured it out by going through your code on GitHub

I will try out non convert approach as well as you outlined below.

I really love your package!  Its awesome.

**Comment by robertmartin8** [comment]
@dao72 

I'm glad you managed to resolve the issue! Do leave a star if you're finding the package useful :)

Cheers,
Robert
